window.CET6_PHRASES = [
  { phrase: "abide by", meaning: "遵守；服从", example: "You must abide by the rules." },
  { phrase: "abound in/with", meaning: "充满；富于", example: "The forest abounds with wildlife." },
  { phrase: "above all", meaning: "最重要的是；尤其是", example: "Above all, stay calm." },
  { phrase: "account for", meaning: "解释；说明；占…比例", example: "Can you account for your actions?" },
  { phrase: "accuse of", meaning: "指控；指责", example: "He was accused of theft." },
  { phrase: "act on", meaning: "按…行动；作用于", example: "We need to act on his advice." },
  { phrase: "adhere to", meaning: "坚持；遵守", example: "Adhere to the principles." },
  { phrase: "adjust to", meaning: "适应；调节", example: "She quickly adjusted to her new job." },
  { phrase: "affiliate with", meaning: "与…联合/隶属", example: "The college is affiliated with the university." },
  { phrase: "agree on/upon", meaning: "对…达成一致", example: "They agreed on a date." },
  { phrase: "ahead of", meaning: "在…之前；领先", example: "She finished ahead of schedule." },
  { phrase: "alien to", meaning: "与…格格不入；不相容", example: "Cruelty is alien to his nature." },
  { phrase: "all at once", meaning: "突然；同时", example: "All at once, the lights went out." },
  { phrase: "all but", meaning: "几乎；除…外全部", example: "The game was all but over." },
  { phrase: "all in all", meaning: "总的来说", example: "All in all, it was a great trip." },
  { phrase: "allow for", meaning: "考虑到；顾及", example: "Allow for traffic delays." },
  { phrase: "along with", meaning: "连同…一起", example: "He brought his friend along with him." },
  { phrase: "amount to", meaning: "总计；相当于", example: "His answer amounted to a refusal." },
  { phrase: "and vice versa", meaning: "反之亦然", example: "I trust him, and vice versa." },
  { phrase: "answer for", meaning: "对…负责", example: "You will answer for your mistakes." },
  { phrase: "anything but", meaning: "绝不；根本不", example: "The task is anything but easy." },
  { phrase: "apart from", meaning: "除了…之外（还有）；除去", example: "Apart from the cost, it's a good idea." },
  { phrase: "appeal to", meaning: "吸引；呼吁；上诉", example: "The film appeals to young audiences." },
  { phrase: "apply for", meaning: "申请", example: "She applied for a scholarship." },
  { phrase: "apply to", meaning: "适用于；应用", example: "These rules apply to everyone." },
  { phrase: "approve of", meaning: "赞成；同意", example: "Do you approve of his decision?" },
  { phrase: "arise from", meaning: "由…引起；起源于", example: "Problems arose from his carelessness." },
  { phrase: "as a result", meaning: "因此；结果", example: "He worked hard; as a result, he succeeded." },
  { phrase: "as for/to", meaning: "至于；关于", example: "As for the others, I don't care." },
  { phrase: "as it were", meaning: "可以说；在某种程度上", example: "He is, as it were, a walking dictionary." },
  { phrase: "as regards", meaning: "关于；至于", example: "As regards your question, I'll answer later." },
  { phrase: "as such", meaning: "本身；相应地", example: "The job, as such, is not difficult." },
  { phrase: "as yet", meaning: "到目前为止；迄今", example: "As yet, no solution has been found." },
  { phrase: "aside from", meaning: "除…之外", example: "Aside from a few scratches, the car was fine." },
  { phrase: "ask after", meaning: "询问…的健康/情况", example: "He asked after your family." },
  { phrase: "assure of", meaning: "使确信；向…保证", example: "I assure you of my support." },
  { phrase: "at a glance", meaning: "一眼；乍看", example: "I saw at a glance that something was wrong." },
  { phrase: "at all events", meaning: "无论如何", example: "At all events, we must be there." },
  { phrase: "at best", meaning: "充其量；至多", example: "At best, we'll finish in two days." },
  { phrase: "at ease", meaning: "安逸；自在", example: "Make yourself at ease." },
  { phrase: "at fault", meaning: "有责任；出毛病", example: "The driver was at fault for the accident." },
  { phrase: "at first glance", meaning: "乍一看", example: "At first glance, the problem seems easy." },
  { phrase: "at intervals", meaning: "不时；每隔…距离/时间", example: "The buses run at 10-minute intervals." },
  { phrase: "at large", meaning: "在逃；详述；总体上", example: "The suspect is still at large." },
  { phrase: "at leisure", meaning: "有空；从容地", example: "Read the book at your leisure." },
  { phrase: "at length", meaning: "最后；详细地", example: "He spoke at length about the plan." },
  { phrase: "at random", meaning: "随机地；任意地", example: "Pick a card at random." },
  { phrase: "at stake", meaning: "在危险中；利害攸关", example: "His career is at stake." },
  { phrase: "at the expense of", meaning: "以…为代价", example: "He succeeded at the expense of his health." },
  { phrase: "at the mercy of", meaning: "任凭…摆布", example: "The ship was at the mercy of the storm." },
  { phrase: "at the risk of", meaning: "冒…的危险", example: "At the risk of being late, I stopped for coffee." },
  { phrase: "at variance with", meaning: "与…不一致/有分歧", example: "His actions are at variance with his words." },
  { phrase: "attend to", meaning: "照料；处理", example: "Attend to your duties." },
  { phrase: "attribute to", meaning: "归因于", example: "She attributes her success to hard work." },
  { phrase: "avail oneself of", meaning: "利用", example: "You should avail yourself of every opportunity." },
  { phrase: "bear on/upon", meaning: "与…有关；对…有影响", example: "How does this bear on the issue?" },
  { phrase: "bear out", meaning: "证实；支持", example: "The evidence bears out his claim." },
  { phrase: "bear with", meaning: "容忍；耐心等待", example: "Bear with me for a moment." },
  { phrase: "become of", meaning: "发生…情况；…遭遇", example: "What became of him after he left?" },
  { phrase: "before long", meaning: "不久以后", example: "Before long, she returned." },
  { phrase: "believe in", meaning: "信仰；信任", example: "I believe in honesty." },
  { phrase: "benefit from", meaning: "从…获益", example: "Everyone can benefit from exercise." },
  { phrase: "beyond belief", meaning: "难以置信", example: "His arrogance is beyond belief." },
  { phrase: "beyond doubt", meaning: "无疑地", example: "The truth is beyond doubt." },
  { phrase: "beyond reach", meaning: "够不着；无法达到", example: "The goal is beyond our reach." },
  { phrase: "boil down to", meaning: "归结为", example: "The argument boils down to money." },
  { phrase: "break down", meaning: "出故障；分解；崩溃", example: "The car broke down." },
  { phrase: "break in", meaning: "闯入；插嘴", example: "Thieves broke in last night." },
  { phrase: "break off", meaning: "折断；中断", example: "They broke off the engagement." },
  { phrase: "break through", meaning: "突破", example: "Scientists broke through in cancer research." },
  { phrase: "break up", meaning: "打碎；分手；散会", example: "They decided to break up." },
  { phrase: "bring about", meaning: "导致；引起", example: "The reforms brought about change." },
  { phrase: "bring forth", meaning: "产生；提出", example: "He brought forth a new plan." },
  { phrase: "bring forward", meaning: "提出；提前", example: "Bring the meeting forward to Monday." },
  { phrase: "bring off", meaning: "成功完成", example: "She brought off a difficult task." },
  { phrase: "bring on", meaning: "引起；促使", example: "Stress brought on his illness." },
  { phrase: "bring out", meaning: "出版；使显现", example: "The crisis brought out his best qualities." },
  { phrase: "bring round/around", meaning: "使苏醒；说服", example: "We finally brought him around to our view." },
  { phrase: "bring up", meaning: "抚养；提出", example: "She brought up three children." },
  { phrase: "brush aside", meaning: "置之不理", example: "He brushed aside my concerns." },
  { phrase: "brush up on", meaning: "复习；重温", example: "I need to brush up on my French." },
  { phrase: "build up", meaning: "积累；增强", example: "Build up your strength." },
  { phrase: "burn out", meaning: "烧尽；耗尽精力", example: "He burned out from overwork." },
  { phrase: "burst into", meaning: "突然…起来", example: "She burst into tears." },
  { phrase: "but for", meaning: "要不是；如果没有", example: "But for your help, I would have failed." },
  { phrase: "by any chance", meaning: "万一；碰巧", example: "Are you, by any chance, looking for a job?" },
  { phrase: "by the same token", meaning: "同样地", example: "By the same token, we must consider cost." },
  { phrase: "by virtue of", meaning: "凭借；由于", example: "He got the job by virtue of his experience." },
  { phrase: "by way of", meaning: "经由；作为", example: "He said it by way of apology." },
  { phrase: "call for", meaning: "需要；要求；去接", example: "The recipe calls for three eggs." },
  { phrase: "call off", meaning: "取消", example: "They called off the meeting." },
  { phrase: "call on/upon", meaning: "拜访；请求；号召", example: "I call on you to help." },
  { phrase: "call up", meaning: "打电话；征召；使想起", example: "The music called up memories." },
  { phrase: "cannot but", meaning: "不得不；禁不住", example: "I cannot but admire his courage." },
  { phrase: "capable of", meaning: "有能力…", example: "She is capable of great things." },
  { phrase: "care for", meaning: "照顾；喜欢", example: "Who will care for the children?" },
  { phrase: "carry forward", meaning: "推进", example: "Carry forward the good work." },
  { phrase: "carry off", meaning: "夺走；赢得", example: "He carried off the first prize." },
  { phrase: "carry on", meaning: "继续", example: "Carry on with your work." },
  { phrase: "carry out", meaning: "执行；实施", example: "Carry out the plan." },
  { phrase: "carry through", meaning: "完成；坚持到底", example: "We carried the project through." },
  { phrase: "catch on", meaning: "理解；流行起来", example: "The new song caught on quickly." },
  { phrase: "catch up with", meaning: "赶上；追上", example: "I need to catch up with my homework." },
  { phrase: "cater to", meaning: "迎合；满足…需要", example: "The hotel caters to business travelers." },
  { phrase: "center on/upon", meaning: "集中于", example: "The debate centered on economic issues." },
  { phrase: "certain of", meaning: "确信", example: "Are you certain of the facts?" },
  { phrase: "charge with", meaning: "控告；使承担", example: "He was charged with theft." },
  { phrase: "check in", meaning: "办理入住/登机", example: "We checked in at the hotel." },
  { phrase: "check out", meaning: "结账离开；检查", example: "Check out the library books." },
  { phrase: "check up on", meaning: "检查；核实", example: "I need to check up on his story." },
  { phrase: "claim to", meaning: "声称；主张", example: "He claims to be an expert." },
  { phrase: "clean out", meaning: "清理；扫除", example: "Clean out the garage." },
  { phrase: "clear away", meaning: "收拾；清除", example: "Clear away the dishes." },
  { phrase: "close down", meaning: "关闭；停业", example: "The factory closed down." },
  { phrase: "coincide with", meaning: "与…巧合；同时发生", example: "His visit coincided with mine." },
  { phrase: "collide with", meaning: "与…碰撞；冲突", example: "The bus collided with a truck." },
  { phrase: "combine with", meaning: "与…结合", example: "Combine the flour with water." },
  { phrase: "come about", meaning: "发生", example: "How did the accident come about?" },
  { phrase: "come across", meaning: "偶然遇见；给人以…印象", example: "He came across as friendly." },
  { phrase: "come along", meaning: "进展；一起来", example: "How is your project coming along?" },
  { phrase: "come apart", meaning: "破碎；破裂", example: "The book came apart in my hands." },
  { phrase: "come around/round", meaning: "苏醒；转变看法", example: "He finally came around to our side." },
  { phrase: "come between", meaning: "离间；妨碍", example: "Don't let money come between you." },
  { phrase: "come by", meaning: "得到；拜访", example: "How did you come by that rare book?" },
  { phrase: "come down to", meaning: "归结为", example: "The issue comes down to trust." },
  { phrase: "come off", meaning: "脱落；成功", example: "The plan didn't come off." },
  { phrase: "come out", meaning: "出版；结果是；出现", example: "The truth came out eventually." },
  { phrase: "come through", meaning: "经历…仍活着；成功", example: "He came through the illness." },
  { phrase: "come to", meaning: "苏醒；总计；达到", example: "The bill came to $50." },
  { phrase: "come up", meaning: "走近；发生；被提及", example: "A problem came up." },
  { phrase: "come up with", meaning: "想出；提出", example: "She came up with a great idea." },
  { phrase: "comment on", meaning: "评论", example: "He refused to comment on the matter." },
  { phrase: "commit to", meaning: "承诺；投入", example: "He committed himself to the cause." },
  { phrase: "compare with/to", meaning: "与…比较", example: "Compared with you, I'm rich." },
  { phrase: "compensate for", meaning: "补偿", example: "Nothing can compensate for the loss." },
  { phrase: "complain of", meaning: "抱怨；诉说", example: "He complained of a headache." },
  { phrase: "comply with", meaning: "遵守；服从", example: "You must comply with the rules." },
  { phrase: "conceive of", meaning: "设想；想象", example: "I cannot conceive of a world without music." },
  { phrase: "concentrate on", meaning: "集中精力于", example: "Concentrate on your work." },
  { phrase: "conform to", meaning: "遵守；符合", example: "The product conforms to safety standards." },
  { phrase: "consent to", meaning: "同意", example: "She consented to the marriage." },
  { phrase: "consist of", meaning: "由…组成", example: "Water consists of hydrogen and oxygen." },
  { phrase: "consist in", meaning: "在于", example: "Happiness consists in contentment." },
  { phrase: "consult with", meaning: "与…商量", example: "Consult with your doctor." },
  { phrase: "contribute to", meaning: "有助于；捐献", example: "Exercise contributes to good health." },
  { phrase: "converge on", meaning: "汇集于；集中于", example: "The crowds converged on the square." },
  { phrase: "convince of", meaning: "使确信", example: "I'm convinced of his innocence." },
  { phrase: "cope with", meaning: "处理；应对", example: "How do you cope with stress?" },
  { phrase: "correspond to/with", meaning: "符合；与…通信", example: "The results correspond with the theory." },
  { phrase: "count on", meaning: "依靠；指望", example: "You can count on me." },
  { phrase: "cover up", meaning: "掩盖", example: "He tried to cover up the truth." },
  { phrase: "credit with", meaning: "把…归功于", example: "He is credited with the discovery." },
  { phrase: "cure of", meaning: "治愈", example: "The medicine cured him of his illness." },
  { phrase: "cut back", meaning: "削减", example: "We must cut back on expenses." },
  { phrase: "cut down", meaning: "砍倒；减少", example: "Cut down on sugar." },
  { phrase: "cut off", meaning: "切断；中断", example: "The power was cut off." },
  { phrase: "cut short", meaning: "打断；缩短", example: "His speech was cut short." },
  { phrase: "deal in", meaning: "经营", example: "He deals in antiques." },
  { phrase: "deal with", meaning: "处理；对付", example: "How do you deal with difficult customers?" },
  { phrase: "dedicate to", meaning: "致力于", example: "She dedicated her life to science." },
  { phrase: "delight in", meaning: "以…为乐", example: "He delights in playing chess." },
  { phrase: "derive from", meaning: "源于", example: "The word derives from Latin." },
  { phrase: "descend from", meaning: "起源；是…的后裔", example: "He descends from a noble family." },
  { phrase: "deviate from", meaning: "偏离", example: "Don't deviate from the plan." },
  { phrase: "die away", meaning: "(声音)渐弱；消失", example: "The sound died away." },
  { phrase: "die out", meaning: "灭绝；消失", example: "Many species have died out." },
  { phrase: "differ from", meaning: "与…不同", example: "His opinion differs from mine." },
  { phrase: "dispose of", meaning: "处理；丢掉", example: "Dispose of the garbage." },
  { phrase: "distinguish from", meaning: "区分", example: "Can you distinguish a frog from a toad?" },
  { phrase: "do away with", meaning: "废除；去掉", example: "They did away with the old rules." },
  { phrase: "do justice to", meaning: "公平对待；充分体现", example: "The photo does not do justice to her beauty." },
  { phrase: "do without", meaning: "没有…也行", example: "We can't do without water." },
  { phrase: "double up", meaning: "弯腰；共用", example: "We'll have to double up in the room." },
  { phrase: "draw in", meaning: "(白天)变短；到站", example: "The train drew in." },
  { phrase: "draw on", meaning: "利用；临近", example: "He drew on his savings." },
  { phrase: "draw up", meaning: "起草；拟定；使停下", example: "They drew up a contract." },
  { phrase: "dream of", meaning: "梦想；向往", example: "I dream of traveling the world." },
  { phrase: "dress up", meaning: "盛装打扮", example: "We dressed up for the party." },
  { phrase: "drop in", meaning: "顺便拜访", example: "Drop in anytime." },
  { phrase: "drop off", meaning: "打瞌睡；放下；减少", example: "The sales dropped off." },
  { phrase: "drop out", meaning: "辍学；退出", example: "He dropped out of college." },
  { phrase: "dwell on/upon", meaning: "详述；老是想着", example: "Don't dwell on the past." },
  { phrase: "embark on/upon", meaning: "开始；着手", example: "He embarked on a new career." },
  { phrase: "emerge from", meaning: "从…出现；摆脱", example: "He emerged from the water." },
  { phrase: "end in", meaning: "以…告终", example: "The argument ended in a fight." },
  { phrase: "end up", meaning: "最终成为；最后", example: "He ended up in prison." },
  { phrase: "engage in", meaning: "参与；从事", example: "They engaged in a debate." },
  { phrase: "enjoy oneself", meaning: "过得愉快", example: "Did you enjoy yourself?" },
  { phrase: "enroll in", meaning: "注册；加入", example: "She enrolled in an art course." },
  { phrase: "enter into", meaning: "开始；进入；成为…一部分", example: "We entered into negotiations." },
  { phrase: "entitle to", meaning: "给…权利", example: "You are entitled to a refund." },
  { phrase: "escape from", meaning: "逃脱", example: "He escaped from prison." },
  { phrase: "even so", meaning: "即使如此", example: "It's raining; even so, we must go." },
  { phrase: "ever since", meaning: "自从", example: "Ever since we met, I've been happy." },
  { phrase: "every so often", meaning: "偶尔", example: "He visits every so often." },
  { phrase: "excel in/at", meaning: "擅长", example: "She excels in math." },
  { phrase: "except for", meaning: "除了…以外", example: "The room was empty except for a chair." },
  { phrase: "exert oneself", meaning: "努力；尽力", example: "He exerted himself to finish the work." },
  { phrase: "expose to", meaning: "暴露于；使接触", example: "Don't expose your skin to the sun." },
  { phrase: "face up to", meaning: "勇敢面对", example: "You must face up to reality." },
  { phrase: "fall back on", meaning: "依赖；求助于", example: "He fell back on his savings." },
  { phrase: "fall behind", meaning: "落后", example: "Don't fall behind in your studies." },
  { phrase: "fall in love with", meaning: "爱上", example: "He fell in love with Paris." },
  { phrase: "fall into", meaning: "陷入；养成", example: "He fell into bad habits." },
  { phrase: "fall on/upon", meaning: "攻击；由…承担", example: "The cost fell on me." },
  { phrase: "fall out", meaning: "争吵；脱落", example: "They fell out over money." },
  { phrase: "fall through", meaning: "失败；落空", example: "The deal fell through." },
  { phrase: "feed on", meaning: "以…为食", example: "Cows feed on grass." },
  { phrase: "feel like", meaning: "想要；感觉像", example: "I feel like a cup of tea." },
  { phrase: "figure out", meaning: "理解；算出", example: "I can't figure out the answer." },
  { phrase: "fill in", meaning: "填写；临时替代", example: "Fill in this form." },
  { phrase: "fill out", meaning: "填写；长胖", example: "Fill out the application." },
  { phrase: "find out", meaning: "查明；发现", example: "We need to find out the truth." },
  { phrase: "finish off", meaning: "完成；消灭", example: "He finished off the leftovers." },
  { phrase: "fit in", meaning: "适应；融入", example: "She fits in well with the group." },
  { phrase: "focus on", meaning: "集中于", example: "Focus on your goal." },
  { phrase: "follow suit", meaning: "仿效", example: "When one student left, the others followed suit." },
  { phrase: "frown upon", meaning: "不赞成", example: "His parents frown upon smoking." },
  { phrase: "get across", meaning: "讲清楚；使理解", example: "I couldn't get my point across." },
  { phrase: "get along with", meaning: "与…相处；进展", example: "She gets along with everyone." },
  { phrase: "get at", meaning: "意指；够得着", example: "What are you getting at?" },
  { phrase: "get away with", meaning: "做坏事而不受惩罚", example: "He thought he could get away with lying." },
  { phrase: "get down to", meaning: "开始认真做", example: "Let's get down to business." },
  { phrase: "get hold of", meaning: "抓住；找到", example: "Where can I get hold of a doctor?" },
  { phrase: "get over", meaning: "克服；从…中恢复", example: "She got over the illness." },
  { phrase: "get rid of", meaning: "摆脱", example: "I can't get rid of this cough." },
  { phrase: "get through", meaning: "完成；通过；接通电话", example: "I finally got through the exam." },
  { phrase: "get together", meaning: "聚会", example: "Let's get together for a meal." },
  { phrase: "give away", meaning: "赠送；泄露", example: "She gave away her secret." },
  { phrase: "give in", meaning: "屈服；让步", example: "Don't give in to pressure." },
  { phrase: "give off", meaning: "发出（光、热、气味）", example: "The fire gives off heat." },
  { phrase: "give out", meaning: "分发；用完；发出", example: "The supplies gave out." },
  { phrase: "give rise to", meaning: "引起；导致", example: "The incident gave rise to protests." },
  { phrase: "give up", meaning: "放弃", example: "Never give up." },
  { phrase: "give way to", meaning: "让位给；被…取代", example: "His anger gave way to tears." },
  { phrase: "go about", meaning: "着手做", example: "How do you go about solving this?" },
  { phrase: "go after", meaning: "追求；追赶", example: "Go after your dreams." },
  { phrase: "go against", meaning: "违反；反对", example: "Don't go against the rules." },
  { phrase: "go along with", meaning: "赞同；配合", example: "I'll go along with your plan." },
  { phrase: "go around/round", meaning: "足够分配；流传", example: "Is there enough food to go around?" },
  { phrase: "go for", meaning: "去取；喜欢；适用于", example: "I'll go for a walk." },
  { phrase: "go into", meaning: "进入；调查；从事", example: "Let's go into the details." },
  { phrase: "go off", meaning: "爆炸；响起；离开", example: "The alarm went off." },
  { phrase: "go over", meaning: "复习；检查", example: "Go over your notes." },
  { phrase: "go through", meaning: "经历；仔细检查", example: "He went through a difficult time." },
  { phrase: "go under", meaning: "沉没；失败", example: "The company went under." },
  { phrase: "go with", meaning: "与…相配；伴随", example: "This shirt goes with these pants." },
  { phrase: "go without", meaning: "没有…也行", example: "We can't go without water." },
  { phrase: "hand down", meaning: "传给后代", example: "The tradition was handed down." },
  { phrase: "hand in", meaning: "上交", example: "Hand in your homework." },
  { phrase: "hand over", meaning: "移交", example: "He handed over the keys." },
  { phrase: "hang about/around", meaning: "闲荡；逗留", example: "Don't hang about here." },
  { phrase: "hang on", meaning: "坚持；抓紧；别挂断", example: "Hang on a minute!" },
  { phrase: "hang up", meaning: "挂断电话", example: "He hung up on me." },
  { phrase: "happen to", meaning: "碰巧；发生于", example: "I happened to see him." },
  { phrase: "have an edge over", meaning: "比…有优势", example: "She has an edge over the competition." },
  { phrase: "have bearing on", meaning: "与…有关", example: "This has no bearing on the issue." },
  { phrase: "have nothing to do with", meaning: "与…无关", example: "That has nothing to do with me." },
  { phrase: "head for", meaning: "朝…方向走", example: "We're heading for home." },
  { phrase: "hear from", meaning: "收到…的消息", example: "I look forward to hearing from you." },
  { phrase: "hear of", meaning: "听说", example: "I've never heard of that." },
  { phrase: "hold back", meaning: "阻止；抑制；隐瞒", example: "She held back her tears." },
  { phrase: "hold on", meaning: "坚持；等待", example: "Hold on, I'll be right there." },
  { phrase: "hold out", meaning: "伸出；坚持；提供希望", example: "Hold out your hand." },
  { phrase: "hold up", meaning: "举起；支撑；耽搁", example: "We were held up in traffic." },
  { phrase: "hunt for", meaning: "搜寻", example: "He is hunting for a job." },
  { phrase: "identify with", meaning: "认同；与…有同感", example: "I can identify with his struggles." },
  { phrase: "impose on/upon", meaning: "强加于", example: "Don't impose your views on me." },
  { phrase: "impress on", meaning: "使铭记", example: "He impressed on me the importance of honesty." },
  { phrase: "improve on/upon", meaning: "改进", example: "We need to improve on last year's performance." },
  { phrase: "in addition to", meaning: "除…之外", example: "In addition to English, he speaks French." },
  { phrase: "in any event", meaning: "无论如何", example: "In any event, we'll arrive on time." },
  { phrase: "in case of", meaning: "如果发生；万一", example: "In case of fire, break the glass." },
  { phrase: "in compliance with", meaning: "遵守", example: "We acted in compliance with the law." },
  { phrase: "in conjunction with", meaning: "与…共同", example: "The event is held in conjunction with the festival." },
  { phrase: "in consequence", meaning: "结果", example: "He was late; in consequence, he missed the meeting." },
  { phrase: "in contrast to", meaning: "与…对比", example: "In contrast to her sister, she is outgoing." },
  { phrase: "in default of", meaning: "因缺少", example: "In default of proper evidence, the case was dropped." },
  { phrase: "in defiance of", meaning: "违抗", example: "He acted in defiance of orders." },
  { phrase: "in excess of", meaning: "超过", example: "Expenses exceeded income by $500." },
  { phrase: "in honor of", meaning: "为纪念", example: "A party was held in his honor." },
  { phrase: "in line with", meaning: "与…一致", example: "His actions are in line with his words." },
  { phrase: "in need of", meaning: "需要", example: "The house is in need of repair." },
  { phrase: "in no way", meaning: "决不", example: "This is in no way acceptable." },
  { phrase: "in order to", meaning: "为了", example: "She studied hard in order to pass." },
  { phrase: "in place of", meaning: "代替", example: "Use honey in place of sugar." },
  { phrase: "in preference to", meaning: "优先于", example: "I choose tea in preference to coffee." },
  { phrase: "in proportion to", meaning: "与…成比例", example: "Pay is in proportion to effort." },
  { phrase: "in pursuit of", meaning: "追求", example: "He traveled in pursuit of knowledge." },
  { phrase: "in relation to", meaning: "关于；与…相比", example: "Prices are low in relation to quality." },
  { phrase: "in response to", meaning: "响应；回答", example: "In response to your query, here is the answer." },
  { phrase: "in return for", meaning: "作为…的回报", example: "He gave a gift in return for her help." },
  { phrase: "in search of", meaning: "寻找", example: "They went in search of treasure." },
  { phrase: "in spite of", meaning: "尽管", example: "In spite of the rain, we went out." },
  { phrase: "in terms of", meaning: "就…而言", example: "In terms of quality, this is best." },
  { phrase: "in the face of", meaning: "面对", example: "He remained calm in the face of danger." },
  { phrase: "in the light of", meaning: "鉴于；根据", example: "In the light of new evidence, he was freed." },
  { phrase: "in the vicinity of", meaning: "在…附近；大约", example: "He lives in the vicinity of the station." },
  { phrase: "in view of", meaning: "考虑到", example: "In view of the weather, we cancelled." },
  { phrase: "indifferent to", meaning: "对…漠不关心", example: "He is indifferent to praise or blame." },
  { phrase: "infer from", meaning: "从…推断", example: "What can we infer from the data?" },
  { phrase: "insist on", meaning: "坚持", example: "He insisted on paying." },
  { phrase: "interfere with", meaning: "干扰；妨碍", example: "Don't interfere with my work." },
  { phrase: "intervene in", meaning: "干涉；介入", example: "The police had to intervene in the dispute." },
  { phrase: "invest in", meaning: "投资于", example: "He invested in stocks." },
  { phrase: "involve in", meaning: "卷入；参与", example: "He was involved in the accident." },
  { phrase: "keep abreast of", meaning: "了解…的最新情况", example: "Read newspapers to keep abreast of events." },
  { phrase: "keep at", meaning: "坚持做", example: "Keep at it; you'll succeed." },
  { phrase: "keep back", meaning: "阻止；隐瞒", example: "She kept back the truth." },
  { phrase: "keep down", meaning: "控制；压制", example: "Keep down your voice." },
  { phrase: "keep from", meaning: "阻止；忍住", example: "I couldn't keep from laughing." },
  { phrase: "keep off", meaning: "让开；不接近", example: "Keep off the grass." },
  { phrase: "keep on", meaning: "继续", example: "Keep on trying." },
  { phrase: "keep to", meaning: "遵守；坚持", example: "Keep to the right." },
  { phrase: "keep up with", meaning: "跟上", example: "I can't keep up with the pace." },
  { phrase: "knock down", meaning: "击倒；拆除", example: "The building was knocked down." },
  { phrase: "knock out", meaning: "击倒；淘汰", example: "He was knocked out in the first round." },
  { phrase: "laugh at", meaning: "嘲笑", example: "Don't laugh at others." },
  { phrase: "launch into", meaning: "开始；投入", example: "He launched into a long speech." },
  { phrase: "lay down", meaning: "放下；规定", example: "Lay down your weapons." },
  { phrase: "lay off", meaning: "解雇；停止", example: "The factory laid off 100 workers." },
  { phrase: "lay out", meaning: "布置；设计；花费", example: "The garden is beautifully laid out." },
  { phrase: "lead to", meaning: "导致", example: "Hard work leads to success." },
  { phrase: "lean on", meaning: "依靠", example: "He leaned on me for support." },
  { phrase: "leave alone", meaning: "不打扰", example: "Leave me alone!" },
  { phrase: "leave behind", meaning: "留下；遗忘", example: "Don't leave your bag behind." },
  { phrase: "leave off", meaning: "停止", example: "Leave off biting your nails." },
  { phrase: "leave out", meaning: "省略；遗漏", example: "You left out the final step." },
  { phrase: "lend itself to", meaning: "适合于", example: "This topic lends itself to discussion." },
  { phrase: "let alone", meaning: "更不用说", example: "He can't walk, let alone run." },
  { phrase: "let down", meaning: "使失望", example: "I won't let you down." },
  { phrase: "let go of", meaning: "放开", example: "Let go of my hand." },
  { phrase: "let off", meaning: "放过；排放", example: "He was let off with a warning." },
  { phrase: "let out", meaning: "释放；发出", example: "He let out a yell." },
  { phrase: "level off", meaning: "趋于平稳", example: "Prices have levelled off." },
  { phrase: "lie in", meaning: "在于", example: "The problem lies in the engine." },
  { phrase: "light up", meaning: "照亮；容光焕发", example: "Her face lit up." },
  { phrase: "live up to", meaning: "不辜负", example: "He lived up to his reputation." },
  { phrase: "long for", meaning: "渴望", example: "She longed for a vacation." },
  { phrase: "look back", meaning: "回顾", example: "Looking back, I regret it." },
  { phrase: "look down on", meaning: "看不起", example: "Don't look down on the poor." },
  { phrase: "look forward to", meaning: "期待", example: "I look forward to seeing you." },
  { phrase: "look into", meaning: "调查", example: "The police are looking into the case." },
  { phrase: "look on/upon", meaning: "看待", example: "He looks on her as a daughter." },
  { phrase: "look out", meaning: "小心", example: "Look out! There's a car." },
  { phrase: "look over", meaning: "检查", example: "Look over the contract." },
  { phrase: "look up to", meaning: "尊敬", example: "I look up to my parents." },
  { phrase: "lose sight of", meaning: "忽略；看不见", example: "Don't lose sight of your goals." },
  { phrase: "major in", meaning: "主修", example: "She majors in English." },
  { phrase: "make allowance for", meaning: "体谅；考虑到", example: "Make allowance for his inexperience." },
  { phrase: "make believe", meaning: "假装", example: "The children made believe they were pirates." },
  { phrase: "make certain", meaning: "确信；弄明白", example: "Make certain you lock the door." },
  { phrase: "make for", meaning: "走向；导致", example: "Early rising makes for good health." },
  { phrase: "make fun of", meaning: "取笑", example: "Don't make fun of him." },
  { phrase: "make of", meaning: "理解；看待", example: "What do you make of this?" },
  { phrase: "make off", meaning: "逃走", example: "The thief made off with the money." },
  { phrase: "make out", meaning: "辨认；理解；填写", example: "I can't make out his signature." },
  { phrase: "make sense", meaning: "有意义；讲得通", example: "That doesn't make sense." },
  { phrase: "make up", meaning: "编造；组成；化妆；弥补", example: "Make up a story." },
  { phrase: "make up for", meaning: "补偿", example: "Hard work makes up for lack of talent." },
  { phrase: "make use of", meaning: "利用", example: "Make use of every opportunity." },
  { phrase: "meet with", meaning: "遭遇；会晤", example: "He met with an accident." },
  { phrase: "might as well", meaning: "倒不如；不妨", example: "We might as well go home." },
  { phrase: "mistake for", meaning: "把…误认为", example: "I mistook him for his brother." },
  { phrase: "mix up", meaning: "混淆", example: "Don't mix up the two words." },
  { phrase: "move in on", meaning: "向…逼近", example: "The wolves moved in on the prey." },
  { phrase: "name after", meaning: "以…命名", example: "The bridge is named after the hero." },
  { phrase: "object to", meaning: "反对", example: "I object to the plan." },
  { phrase: "occur to", meaning: "被想起", example: "It never occurred to me." },
  { phrase: "open up", meaning: "打开；开发；吐露", example: "Open up the door." },
  { phrase: "originate from/in", meaning: "起源", example: "The idea originated in Japan." },
  { phrase: "owe to", meaning: "归功于；欠", example: "I owe my success to you." },
  { phrase: "pass away", meaning: "去世", example: "His grandfather passed away." },
  { phrase: "pass by", meaning: "经过", example: "He passed by without a word." },
  { phrase: "pass off as", meaning: "冒充", example: "He passed himself off as a doctor." },
  { phrase: "pass on", meaning: "传递；继续", example: "Pass on the message." },
  { phrase: "pass out", meaning: "昏倒；分发", example: "He passed out from the heat." },
  { phrase: "pass over", meaning: "忽略", example: "They passed over him for promotion." },
  { phrase: "pass up", meaning: "放弃", example: "Don't pass up this chance." },
  { phrase: "pay attention to", meaning: "注意", example: "Pay attention to the teacher." },
  { phrase: "pay back", meaning: "偿还；报复", example: "I'll pay you back tomorrow." },
  { phrase: "pay off", meaning: "还清；成功", example: "His hard work paid off." },
  { phrase: "pay up", meaning: "付清", example: "You must pay up by Friday." },
  { phrase: "pick out", meaning: "挑选；辨认", example: "Pick out the red one." },
  { phrase: "pick up", meaning: "捡起；接人；学会；好转", example: "Pick up the phone." },
  { phrase: "play a part in", meaning: "在…中起作用", example: "He played a part in the success." },
  { phrase: "plug in", meaning: "插上插头", example: "Plug in the charger." },
  { phrase: "point out", meaning: "指出", example: "He pointed out my mistake." },
  { phrase: "prefer to", meaning: "更喜欢", example: "I prefer tea to coffee." },
  { phrase: "prepare for", meaning: "为…做准备", example: "Prepare for the worst." },
  { phrase: "preside over", meaning: "主持", example: "He presided over the meeting." },
  { phrase: "prevail over", meaning: "战胜", example: "Justice will prevail over evil." },
  { phrase: "prevent from", meaning: "阻止", example: "The rain prevented us from going." },
  { phrase: "prior to", meaning: "在…之前", example: "Prior to the meeting, we discussed." },
  { phrase: "profit from", meaning: "从…中获益", example: "He profited from the experience." },
  { phrase: "provide for", meaning: "供养；为…做准备", example: "He provides for his family." },
  { phrase: "pull down", meaning: "拆毁", example: "The old building was pulled down." },
  { phrase: "pull in", meaning: "(车)进站；吸引", example: "The train pulled in." },
  { phrase: "pull off", meaning: "成功完成", example: "He pulled off a miracle." },
  { phrase: "pull out", meaning: "拔出；(车)开出", example: "He pulled out a gun." },
  { phrase: "pull through", meaning: "渡过难关", example: "He pulled through the illness." },
  { phrase: "pull up", meaning: "(使)停下", example: "The car pulled up at the curb." },
  { phrase: "put aside", meaning: "储存；撇开", example: "Put aside some money." },
  { phrase: "put away", meaning: "收起；放好", example: "Put away your toys." },
  { phrase: "put down", meaning: "放下；记下；镇压", example: "Put down your name." },
  { phrase: "put forward", meaning: "提出", example: "He put forward a new theory." },
  { phrase: "put off", meaning: "推迟", example: "Don't put off till tomorrow." },
  { phrase: "put on", meaning: "穿上；上演", example: "Put on your coat." },
  { phrase: "put out", meaning: "熄灭；生产；出版", example: "Put out the fire." },
  { phrase: "put through", meaning: "接通电话；使经历", example: "Put me through to the manager." },
  { phrase: "put up", meaning: "建造；举起；留宿", example: "Put up a tent." },
  { phrase: "put up with", meaning: "忍受", example: "I can't put up with the noise." },
  { phrase: "reason with", meaning: "与…讲道理", example: "You can't reason with a child." },
  { phrase: "reckon with", meaning: "考虑到；处理", example: "We must reckon with the consequences." },
  { phrase: "reconcile to", meaning: "使甘心于", example: "He reconciled himself to the situation." },
  { phrase: "refer to", meaning: "提到；参考", example: "Please refer to the manual." },
  { phrase: "refer to … as", meaning: "把…称为", example: "He is referred to as a genius." },
  { phrase: "reflect on", meaning: "反思；给…带来影响", example: "Reflect on your mistakes." },
  { phrase: "rely on", meaning: "依靠", example: "You can rely on me." },
  { phrase: "remark on", meaning: "评论", example: "He remarked on the weather." },
  { phrase: "remind of", meaning: "使想起", example: "You remind me of your father." },
  { phrase: "resign oneself to", meaning: "顺从于", example: "He resigned himself to fate." },
  { phrase: "resort to", meaning: "诉诸", example: "Don't resort to violence." },
  { phrase: "respond to", meaning: "回答；对…反应", example: "He didn't respond to my question." },
  { phrase: "rest on/upon", meaning: "依靠；基于", example: "The argument rests on false assumptions." },
  { phrase: "result from", meaning: "由…引起", example: "Sickness resulted from overwork." },
  { phrase: "result in", meaning: "导致", example: "The fire resulted in huge damage." },
  { phrase: "revolve around", meaning: "围绕；以…为中心", example: "The earth revolves around the sun." },
  { phrase: "ring up", meaning: "打电话", example: "Ring me up later." },
  { phrase: "rob of", meaning: "抢劫；剥夺", example: "He was robbed of his wallet." },
  { phrase: "rule out", meaning: "排除", example: "We cannot rule out the possibility." },
  { phrase: "run across", meaning: "偶然遇见", example: "I ran across an old friend." },
  { phrase: "run after", meaning: "追赶；追求", example: "He ran after the bus." },
  { phrase: "run away", meaning: "逃跑", example: "Don't run away from problems." },
  { phrase: "run down", meaning: "撞倒；耗尽；说坏话", example: "He was run down by a car." },
  { phrase: "run into", meaning: "偶然遇到；撞上", example: "We ran into trouble." },
  { phrase: "run out", meaning: "用完", example: "We've run out of milk." },
  { phrase: "run over", meaning: "碾过；超过", example: "He was run over by a truck." },
  { phrase: "run through", meaning: "贯穿；匆匆检查", example: "Run through the list." },
  { phrase: "scrape through", meaning: "勉强通过", example: "He scraped through the exam." },
  { phrase: "see about", meaning: "处理；考虑", example: "I'll see about getting a ticket." },
  { phrase: "see off", meaning: "送行", example: "We went to see him off." },
  { phrase: "see through", meaning: "看穿；识破", example: "I can see through your lies." },
  { phrase: "see to", meaning: "负责；照料", example: "See to the arrangements." },
  { phrase: "seek after", meaning: "追求", example: "Happiness is something to be sought after." },
  { phrase: "seize on/upon", meaning: "抓住（机会等）", example: "He seized on the excuse." },
  { phrase: "send for", meaning: "派人去请", example: "Send for a doctor." },
  { phrase: "send in", meaning: "提交", example: "Send in your application." },
  { phrase: "send off", meaning: "邮寄；送别", example: "Send off the package." },
  { phrase: "sentence to", meaning: "判处", example: "He was sentenced to death." },
  { phrase: "serve as", meaning: "充当", example: "This room serves as a study." },
  { phrase: "set about", meaning: "开始做", example: "He set about cleaning the house." },
  { phrase: "set apart", meaning: "使分离；使出众", example: "His intelligence sets him apart." },
  { phrase: "set aside", meaning: "留出；拨出", example: "Set aside some money." },
  { phrase: "set back", meaning: "推迟；花费", example: "The project was set back." },
  { phrase: "set down", meaning: "记下", example: "Set down your thoughts." },
  { phrase: "set off", meaning: "出发；引爆", example: "We set off at dawn." },
  { phrase: "set out", meaning: "出发；开始；陈述", example: "He set out to write a novel." },
  { phrase: "set up", meaning: "建立", example: "They set up a company." },
  { phrase: "settle down", meaning: "定居；安静下来", example: "When will you settle down?" },
  { phrase: "settle for", meaning: "勉强接受", example: "Don't settle for less." },
  { phrase: "settle on", meaning: "选定", example: "We settled on a date." },
  { phrase: "shake off", meaning: "摆脱", example: "Shake off the cold." },
  { phrase: "share in", meaning: "分享", example: "Everyone shared in the joy." },
  { phrase: "shoot at", meaning: "向…射击", example: "He shot at the target." },
  { phrase: "show off", meaning: "炫耀", example: "Stop showing off." },
  { phrase: "show up", meaning: "出现；揭露", example: "He didn't show up." },
  { phrase: "shrug off", meaning: "对…不屑一顾", example: "He shrugged off the criticism." },
  { phrase: "shut down", meaning: "关闭", example: "The factory shut down." },
  { phrase: "shut off", meaning: "关掉；切断", example: "Shut off the water." },
  { phrase: "shut up", meaning: "闭嘴", example: "Shut up!" },
  { phrase: "side with", meaning: "支持；站在…一边", example: "I side with the workers." },
  { phrase: "signal to", meaning: "向…发信号", example: "He signaled to the waiter." },
  { phrase: "sit in on", meaning: "列席", example: "He sat in on the meeting." },
  { phrase: "size up", meaning: "估计", example: "He sized up the situation." },
  { phrase: "slow down", meaning: "减速", example: "Slow down, please." },
  { phrase: "soak up", meaning: "吸收", example: "Sponges soak up water." },
  { phrase: "sort out", meaning: "整理；解决", example: "Sort out the problem." },
  { phrase: "speak for", meaning: "代表…说话", example: "I speak for everyone." },
  { phrase: "specialize in", meaning: "专攻", example: "He specializes in law." },
  { phrase: "speed up", meaning: "加速", example: "Speed up the process." },
  { phrase: "stand by", meaning: "支持；袖手旁观；准备", example: "I'll stand by you." },
  { phrase: "stand for", meaning: "代表；容忍", example: "What does this letter stand for?" },
  { phrase: "stand out", meaning: "突出", example: "Her red dress stood out." },
  { phrase: "stand up for", meaning: "维护", example: "Stand up for your rights." },
  { phrase: "stand up to", meaning: "勇敢面对", example: "He stood up to the bully." },
  { phrase: "start off", meaning: "出发；开始", example: "We started off early." },
  { phrase: "start out", meaning: "开始；起初", example: "He started out as a clerk." },
  { phrase: "stay up", meaning: "熬夜", example: "I stayed up late." },
  { phrase: "stem from", meaning: "起源于", example: "His fears stem from childhood." },
  { phrase: "step in", meaning: "介入", example: "The police stepped in." },
  { phrase: "step up", meaning: "增加；提升", example: "Step up production." },
  { phrase: "stick out", meaning: "伸出；显眼", example: "Stick out your tongue." },
  { phrase: "stick to", meaning: "坚持", example: "Stick to your principles." },
  { phrase: "stop by", meaning: "顺便拜访", example: "I'll stop by later." },
  { phrase: "store up", meaning: "储存", example: "Store up food for winter." },
  { phrase: "stray from", meaning: "偏离", example: "Don't stray from the topic." },
  { phrase: "strike out", meaning: "开始；划掉", example: "He struck out on his own." },
  { phrase: "strive for", meaning: "努力争取", example: "Strive for excellence." },
  { phrase: "subscribe to", meaning: "订阅；同意", example: "I subscribe to the magazine." },
  { phrase: "succeed in", meaning: "在…方面成功", example: "He succeeded in business." },
  { phrase: "suffer from", meaning: "患…病；受…苦", example: "She suffers from headaches." },
  { phrase: "sum up", meaning: "总结", example: "To sum up, we need more time." },
  { phrase: "surrender to", meaning: "投降", example: "They surrendered to the enemy." },
  { phrase: "take after", meaning: "长得像", example: "She takes after her mother." },
  { phrase: "take apart", meaning: "拆开", example: "Take the clock apart." },
  { phrase: "take back", meaning: "收回", example: "I take back what I said." },
  { phrase: "take care of", meaning: "照顾；处理", example: "Take care of the children." },
  { phrase: "take charge", meaning: "负责", example: "He took charge of the project." },
  { phrase: "take delight in", meaning: "以…为乐", example: "He takes delight in reading." },
  { phrase: "take down", meaning: "记下；拆卸", example: "Take down the notes." },
  { phrase: "take effect", meaning: "生效", example: "The drug took effect." },
  { phrase: "take for", meaning: "误认为", example: "I took him for a doctor." },
  { phrase: "take for granted", meaning: "认为理所当然", example: "Don't take your health for granted." },
  { phrase: "take in", meaning: "吸收；理解；欺骗", example: "I took in the whole scene." },
  { phrase: "take into account", meaning: "考虑", example: "Take everything into account." },
  { phrase: "take off", meaning: "起飞；脱下；开始成功", example: "The plane took off." },
  { phrase: "take on", meaning: "承担；呈现", example: "He took on too much work." },
  { phrase: "take over", meaning: "接管", example: "He took over the business." },
  { phrase: "take part in", meaning: "参加", example: "Take part in the game." },
  { phrase: "take place", meaning: "发生", example: "The meeting took place yesterday." },
  { phrase: "take pride in", meaning: "以…自豪", example: "She takes pride in her work." },
  { phrase: "take stock of", meaning: "评估；盘点", example: "Take stock of your situation." },
  { phrase: "take to", meaning: "开始喜欢；开始从事", example: "He took to swimming." },
  { phrase: "take turns", meaning: "轮流", example: "We took turns driving." },
  { phrase: "take up", meaning: "开始从事；占据", example: "She took up painting." },
  { phrase: "talk into", meaning: "说服", example: "He talked me into going." },
  { phrase: "talk out of", meaning: "说服…不做", example: "She talked him out of quitting." },
  { phrase: "talk over", meaning: "讨论", example: "Let's talk it over." },
  { phrase: "team up with", meaning: "与…合作", example: "They teamed up for the project." },
  { phrase: "tear down", meaning: "拆毁", example: "They tore down the old building." },
  { phrase: "tear up", meaning: "撕毁", example: "He tore up the letter." },
  { phrase: "tell apart", meaning: "区分", example: "Can you tell the twins apart?" },
  { phrase: "tend to", meaning: "倾向于；照料", example: "He tends to be late." },
  { phrase: "think better of", meaning: "经考虑改变主意", example: "He thought better of it." },
  { phrase: "think of … as", meaning: "把…看作", example: "I think of him as a friend." },
  { phrase: "think over", meaning: "仔细考虑", example: "Think it over." },
  { phrase: "throw away", meaning: "扔掉", example: "Don't throw away the receipt." },
  { phrase: "throw light on", meaning: "阐明", example: "This evidence throws light on the case." },
  { phrase: "throw up", meaning: "呕吐；放弃", example: "He threw up his meal." },
  { phrase: "tie up", meaning: "系紧；占用", example: "The traffic was tied up." },
  { phrase: "touch on", meaning: "谈及", example: "He touched on many topics." },
  { phrase: "track down", meaning: "追查到", example: "The police tracked down the suspect." },
  { phrase: "trade off", meaning: "权衡", example: "There's a trade-off between speed and quality." },
  { phrase: "try on", meaning: "试穿", example: "Try on this shirt." },
  { phrase: "try out", meaning: "试用", example: "Try out the new software." },
  { phrase: "tune in", meaning: "收听；收看", example: "Tune in tomorrow for more." },
  { phrase: "turn down", meaning: "关小；拒绝", example: "She turned down the offer." },
  { phrase: "turn in", meaning: "上交；睡觉", example: "Turn in your homework." },
  { phrase: "turn off", meaning: "关掉", example: "Turn off the light." },
  { phrase: "turn on", meaning: "打开", example: "Turn on the TV." },
  { phrase: "turn out", meaning: "结果是；生产", example: "It turned out to be true." },
  { phrase: "turn over", meaning: "翻过来；移交", example: "Turn over the page." },
  { phrase: "turn to", meaning: "转向；求助于", example: "He turned to me for help." },
  { phrase: "turn up", meaning: "出现；调大", example: "He turned up late." },
  { phrase: "use up", meaning: "用完", example: "We used up all the paper." },
  { phrase: "vary from", meaning: "不同于", example: "Opinions vary from person to person." },
  { phrase: "venture into", meaning: "冒险进入", example: "He ventured into a new field." },
  { phrase: "wait on", meaning: "服侍", example: "She waited on the customers." },
  { phrase: "wake up", meaning: "醒来", example: "Wake up at seven." },
  { phrase: "ward off", meaning: "避开", example: "He warded off the blow." },
  { phrase: "warm up", meaning: "热身", example: "Warm up before exercise." },
  { phrase: "wash up", meaning: "洗餐具；洗手", example: "I'll wash up after dinner." },
  { phrase: "watch out", meaning: "当心", example: "Watch out for cars!" },
  { phrase: "wear off", meaning: "逐渐消失", example: "The effect wore off." },
  { phrase: "wear out", meaning: "穿破；使疲乏", example: "I'm worn out." },
  { phrase: "weigh up", meaning: "权衡", example: "Weigh up the pros and cons." },
  { phrase: "wind up", meaning: "结束；上发条", example: "Let's wind up the meeting." },
  { phrase: "wipe out", meaning: "消灭", example: "The disease was wiped out." },
  { phrase: "work at", meaning: "从事于", example: "He is working at his new novel." },
  { phrase: "work off", meaning: "消除；发泄", example: "Work off your anger." },
  { phrase: "work out", meaning: "解决；锻炼；结果", example: "Work out the problem." },
  { phrase: "write off", meaning: "注销；认为…无用", example: "The debt was written off." },
  { phrase: "yield to", meaning: "屈服", example: "Don't yield to temptation." }
];
