window.CET6_PHRASES = [
  { phrase: "a case in point", meaning: "恰当的例子", example: "This problem is a case in point." },
  { phrase: "a far cry from", meaning: "与…相差甚远", example: "His second book is a far cry from his first." },
  { phrase: "a fraction of", meaning: "一小部分", example: "I only spent a fraction of my salary." },
  { phrase: "a multitude of", meaning: "大量的，许多", example: "A multitude of factors led to the failure." },
  { phrase: "a multitude of", meaning: "许多，大量", example: "A multitude of problems remain unsolved." },
  { phrase: "a point of view", meaning: "观点，看法", example: "From my point of view, it's unfair." },
  { phrase: "a touch of", meaning: "少许，一点", example: "Add a touch of salt to the soup." },
  { phrase: "abide by", meaning: "遵守，信守", example: "You must abide by the rules." },
  { phrase: "above all", meaning: "最重要的是；尤其是", example: "Above all, be honest." },
  { phrase: "abound in / with", meaning: "充满，富于", example: "The river abounds with fish." },
  { phrase: "access to", meaning: "接近（或进入）…的机会/权利", example: "Students need access to the library." },
  { phrase: "according to", meaning: "根据，按照", example: "According to the report, sales increased." },
  { phrase: "account for", meaning: "解释；占（比例）", example: "How do you account for the missing money?" },
  { phrase: "accuse … of", meaning: "控告某人……；谴责某人……", example: "She was accused of stealing." },
  { phrase: "acquaint oneself with", meaning: "使认识，使了解", example: "I need to acquaint myself with the new software." },
  { phrase: "act on", meaning: "按…行事；对…起作用", example: "Act on your teacher's advice." },
  { phrase: "add up to", meaning: "总计达；意味着", example: "The total adds up to 500." },
  { phrase: "adhere to", meaning: "坚持；遵守；黏附", example: "We must adhere to the plan." },
  { phrase: "after all", meaning: "毕竟，终究", example: "After all, he is just a child." },
  { phrase: "again and again", meaning: "再三地，反复地", example: "He asked the same question again and again." },
  { phrase: "agree on", meaning: "对…达成一致", example: "We agreed on a plan." },
  { phrase: "agree to", meaning: "同意（计划、建议等）", example: "She agreed to the proposal." },
  { phrase: "agree with", meaning: "同意某人；与…相符", example: "I agree with you." },
  { phrase: "ahead of", meaning: "在…前面；早于", example: "She arrived ahead of time." },
  { phrase: "ahead of schedule", meaning: "提前", example: "We finished the project ahead of schedule." },
  { phrase: "aim at", meaning: "瞄准；旨在，致力于", example: "This campaign aims at young people." },
  { phrase: "all at once", meaning: "突然；同时", example: "All at once, the lights went out." },
  { phrase: "all but", meaning: "几乎，差不多", example: "The game was all but over." },
  { phrase: "all in all", meaning: "总的来说，大体而言", example: "All in all, it was a good trip." },
  { phrase: "all of a sudden", meaning: "突然", example: "All of a sudden, the lights went out." },
  { phrase: "all over", meaning: "到处；遍及；结束", example: "I looked all over for my keys." },
  { phrase: "all the same", meaning: "仍然，还是", example: "He's not perfect, but I love him all the same." },
  { phrase: "allow for", meaning: "考虑到；顾及；允许有", example: "We must allow for delays." },
  { phrase: "along with", meaning: "与…一起", example: "She came along with her mother." },
  { phrase: "amount to", meaning: "总计达；等于，相当于", example: "His answer amounted to a refusal." },
  { phrase: "and so forth", meaning: "等等", example: "She bought apples, oranges, and so forth." },
  { phrase: "answer for", meaning: "对…负责；为…担保", example: "You will have to answer for your actions." },
  { phrase: "anything but", meaning: "根本不；绝不", example: "He is anything but stupid." },
  { phrase: "apart from", meaning: "除…之外", example: "Apart from the cost, it's a good idea." },
  { phrase: "appeal to", meaning: "吸引；呼吁", example: "The movie appeals to all ages." },
  { phrase: "apply for", meaning: "申请", example: "I applied for a new job." },
  { phrase: "apply oneself to", meaning: "致力于…，专心于…", example: "Apply yourself to your studies." },
  { phrase: "approve of", meaning: "赞成，批准", example: "Her parents don't approve of the marriage." },
  { phrase: "around the corner", meaning: "即将来临；在拐角处", example: "Spring is just around the corner." },
  { phrase: "as a matter of fact", meaning: "事实上，其实", example: "As a matter of fact, I agree with you." },
  { phrase: "as a result", meaning: "结果，因此", example: "He worked hard; as a result, he succeeded." },
  { phrase: "as a rule", meaning: "通常，一般说来", example: "As a rule, I get up at six." },
  { phrase: "as far as", meaning: "就…而言；至于", example: "As far as I know, he is reliable." },
  { phrase: "as follows", meaning: "如下", example: "The results are as follows." },
  { phrase: "as for", meaning: "至于，关于", example: "As for me, I prefer tea." },
  { phrase: "as if / as though", meaning: "好像，仿佛", example: "He acts as if he owns the place." },
  { phrase: "as long as", meaning: "只要；既然", example: "You can stay as long as you like." },
  { phrase: "as regards", meaning: "关于，至于", example: "As regards your question, I'll reply later." },
  { phrase: "as soon as", meaning: "一…就…", example: "Come as soon as possible." },
  { phrase: "as to", meaning: "关于，至于", example: "He asked as to my plans." },
  { phrase: "as usual", meaning: "像往常一样，照例", example: "She is late, as usual." },
  { phrase: "as well", meaning: "也，同样地", example: "I can do it as well." },
  { phrase: "as well as", meaning: "以及；和…一样", example: "He speaks English as well as French." },
  { phrase: "associate with", meaning: "与…交往；联系", example: "Don't associate with bad people." },
  { phrase: "at a loss", meaning: "困惑，不知所措", example: "I'm at a loss for words." },
  { phrase: "at a time", meaning: "每次；一次", example: "Take one pill at a time." },
  { phrase: "at all", meaning: "根本，丝毫", example: "I don't like it at all." },
  { phrase: "at all costs", meaning: "不惜任何代价", example: "We must avoid war at all costs." },
  { phrase: "at any rate", meaning: "无论如何；至少", example: "At any rate, we must finish today." },
  { phrase: "at best", meaning: "充其量，至多", example: "At best, we'll arrive by noon." },
  { phrase: "at ease", meaning: "自在，舒适；稍息", example: "Stand at ease." },
  { phrase: "at first", meaning: "最初，起先", example: "At first, I found it difficult." },
  { phrase: "at hand", meaning: "在手边；即将到来", example: "Help is at hand." },
  { phrase: "at heart", meaning: "本质上；内心里", example: "He's a kind person at heart." },
  { phrase: "at home", meaning: "在家；在国内；舒适自在", example: "Make yourself at home." },
  { phrase: "at intervals", meaning: "不时；每隔…距离/时间", example: "Trees are planted at intervals along the road." },
  { phrase: "at large", meaning: "在逃；总体上；详细地", example: "The suspect is still at large." },
  { phrase: "at length", meaning: "最后；详细地", example: "He described the trip at length." },
  { phrase: "at one time", meaning: "曾经，一度", example: "At one time, this was a busy port." },
  { phrase: "at present", meaning: "目前，现在", example: "At present, he is abroad." },
  { phrase: "at random", meaning: "随便地，任意地", example: "Choose a number at random." },
  { phrase: "at stake", meaning: "在危急关头，有风险", example: "Thousands of lives are at stake." },
  { phrase: "at the cost of", meaning: "以…为代价", example: "He succeeded at the cost of his health." },
  { phrase: "at the expense of", meaning: "以…为代价", example: "He worked hard at the expense of his health." },
  { phrase: "at the mercy of", meaning: "任…摆布，受…支配", example: "We were at the mercy of the weather." },
  { phrase: "at the moment", meaning: "此刻，目前", example: "I'm busy at the moment." },
  { phrase: "at the risk of", meaning: "冒着…的危险", example: "He saved the child at the risk of his own life." },
  { phrase: "at the same time", meaning: "同时；然而", example: "I like it, but at the same time I'm worried." },
  { phrase: "at times", meaning: "有时，间或", example: "At times, I feel lonely." },
  { phrase: "attach importance to", meaning: "重视…", example: "We attach importance to education." },
  { phrase: "avail (oneself) of", meaning: "利用（机会等）", example: "You should avail yourself of this opportunity." },
  { phrase: "back and forth", meaning: "来回地；反复地", example: "He paced back and forth." },
  { phrase: "back up", meaning: "支持；倒退；备份", example: "Back up your files regularly." },
  { phrase: "based on", meaning: "以…为基础", example: "The film is based on a true story." },
  { phrase: "be about to", meaning: "即将，正要", example: "The show is about to start." },
  { phrase: "be absorbed in", meaning: "全神贯注于…", example: "She is absorbed in her book." },
  { phrase: "be accustomed to", meaning: "习惯于", example: "I'm accustomed to early rising." },
  { phrase: "be aware of", meaning: "知道，意识到", example: "Are you aware of the problem?" },
  { phrase: "be bound to", meaning: "一定，必定", example: "He's bound to succeed." },
  { phrase: "be capable of", meaning: "有能力做…", example: "She is capable of doing the job." },
  { phrase: "be concerned about", meaning: "关心；担忧", example: "She is concerned about her health." },
  { phrase: "be fed up with", meaning: "对…感到厌烦", example: "I'm fed up with his complaints." },
  { phrase: "be fond of", meaning: "喜欢，喜爱", example: "He is fond of music." },
  { phrase: "be in love with", meaning: "爱上…", example: "He's in love with her." },
  { phrase: "be involved in", meaning: "卷入；参与", example: "He was involved in a car accident." },
  { phrase: "be lacking in", meaning: "缺少…", example: "He is lacking in confidence." },
  { phrase: "be lost in thought", meaning: "陷入沉思", example: "She sat there, lost in thought." },
  { phrase: "be obliged to", meaning: "不得不；感激", example: "I'm much obliged to you for your help." },
  { phrase: "be on a diet", meaning: "节食", example: "She's on a diet to lose weight." },
  { phrase: "be prone to", meaning: "易于…的，有…倾向的", example: "He is prone to colds." },
  { phrase: "be satisfied with", meaning: "对…满意", example: "Are you satisfied with the result?" },
  { phrase: "be short of", meaning: "缺乏，不足", example: "We're short of money." },
  { phrase: "be sick of", meaning: "厌恶，厌倦", example: "I'm sick of this weather." },
  { phrase: "be subject to", meaning: "受…支配；易受…的", example: "The schedule is subject to change." },
  { phrase: "be suitable for", meaning: "适合…", example: "This film is suitable for children." },
  { phrase: "be supposed to", meaning: "应该，被期望", example: "You are supposed to be here by 8." },
  { phrase: "be used to", meaning: "习惯于", example: "He is used to hard work." },
  { phrase: "bear … in mind", meaning: "记住…", example: "Bear in mind that it may rain." },
  { phrase: "beat down", meaning: "打倒；杀价；强烈照射", example: "The sun beat down on us." },
  { phrase: "because of", meaning: "因为，由于", example: "The game was cancelled because of rain." },
  { phrase: "before long", meaning: "不久以后", example: "Before long, she will return." },
  { phrase: "behind schedule", meaning: "落后于预定计划", example: "The project is behind schedule." },
  { phrase: "believe in", meaning: "信任；信仰", example: "Do you believe in ghosts?" },
  { phrase: "belong to", meaning: "属于", example: "This book belongs to me." },
  { phrase: "benefit from", meaning: "从…中获益", example: "You can benefit from regular exercise." },
  { phrase: "beyond compare", meaning: "无与伦比", example: "His talent is beyond compare." },
  { phrase: "beyond control", meaning: "无法控制", example: "The fire was beyond control." },
  { phrase: "beyond description", meaning: "无法形容", example: "The scenery was beyond description." },
  { phrase: "beyond question", meaning: "毫无疑问", example: "Her honesty is beyond question." },
  { phrase: "beyond repair", meaning: "无法修复", example: "The machine is beyond repair." },
  { phrase: "bit by bit", meaning: "一点一点地，逐渐地", example: "Bit by bit, he improved." },
  { phrase: "black and blue", meaning: "青一块紫一块", example: "He was beaten black and blue." },
  { phrase: "blame … for", meaning: "因…责怪某人", example: "Don't blame me for the mistake." },
  { phrase: "blow up", meaning: "爆炸；给…充气；放大", example: "The balloon blew up." },
  { phrase: "boast about / of", meaning: "自夸，夸耀", example: "He boasted about his success." },
  { phrase: "break away", meaning: "脱离；逃脱", example: "He broke away from the guards." },
  { phrase: "break down", meaning: "出故障；分解；打破；感情崩溃", example: "My car broke down." },
  { phrase: "break in", meaning: "闯入；插嘴；驯服", example: "Thieves broke in last night." },
  { phrase: "break out", meaning: "爆发；突然发生", example: "A fire broke out last night." },
  { phrase: "break through", meaning: "突破，冲破", example: "Scientists have broken through in cancer research." },
  { phrase: "break up", meaning: "打碎；分手；散会", example: "They decided to break up." },
  { phrase: "bring about", meaning: "导致，引起", example: "The reforms brought about great change." },
  { phrase: "bring back", meaning: "带回；使回忆起；恢复", example: "The song brings back memories." },
  { phrase: "bring down", meaning: "降低；打倒；击落", example: "We need to bring down costs." },
  { phrase: "bring forward", meaning: "提出；提前", example: "Bring forward your proposal at the meeting." },
  { phrase: "bring out", meaning: "出版；使显现；激发", example: "He brought out his best performance." },
  { phrase: "bring up", meaning: "抚养；提出；呕吐", example: "She brought up three children." },
  { phrase: "brush up", meaning: "复习；提高", example: "I need to brush up my French." },
  { phrase: "build up", meaning: "逐步建立；积聚；增强", example: "Build up your confidence." },
  { phrase: "burn down", meaning: "烧毁", example: "The old house burned down." },
  { phrase: "burn out", meaning: "烧光；耗尽精力", example: "Don't burn yourself out." },
  { phrase: "burst into", meaning: "突然…起来（眼泪/笑声）", example: "She burst into tears." },
  { phrase: "but for", meaning: "要不是，如果没有", example: "But for your help, I would have failed." },
  { phrase: "by accident", meaning: "偶然，意外地", example: "I met her by accident." },
  { phrase: "by all means", meaning: "当然可以；尽一切办法", example: "By all means, take a look." },
  { phrase: "by and by", meaning: "不久；渐渐", example: "By and by, things got better." },
  { phrase: "by chance", meaning: "偶然，碰巧", example: "I found it by chance." },
  { phrase: "by hand", meaning: "用手；手工的", example: "The letter was delivered by hand." },
  { phrase: "by heart", meaning: "熟记，背出", example: "Learn the poem by heart." },
  { phrase: "by means of", meaning: "用，凭借", example: "He succeeded by means of hard work." },
  { phrase: "by mistake", meaning: "错误地", example: "I took your bag by mistake." },
  { phrase: "by nature", meaning: "天生地；本性上", example: "He is shy by nature." },
  { phrase: "by no means", meaning: "绝不，并没有", example: "This is by no means easy." },
  { phrase: "by the way", meaning: "顺便说，附带说说", example: "By the way, have you seen John?" },
  { phrase: "call back", meaning: "回电话；召回", example: "I'll call you back later." },
  { phrase: "call for", meaning: "需要；要求；去接（某人）", example: "This recipe calls for three eggs." },
  { phrase: "call off", meaning: "取消", example: "They called off the meeting." },
  { phrase: "call on", meaning: "拜访；号召", example: "I'll call on you tomorrow." },
  { phrase: "calm down", meaning: "平静下来；使冷静", example: "Calm down and tell me what happened." },
  { phrase: "care about", meaning: "关心；在意", example: "Do you care about the environment?" },
  { phrase: "care for", meaning: "照顾；喜欢", example: "Who will care for the children?" },
  { phrase: "carry off", meaning: "拿走；夺走；赢得", example: "He carried off the prize." },
  { phrase: "carry on", meaning: "继续；进行", example: "Let's carry on with the work." },
  { phrase: "carry out", meaning: "执行，实施；完成", example: "They carried out the plan." },
  { phrase: "catch fire", meaning: "着火", example: "The dry wood caught fire easily." },
  { phrase: "catch up with", meaning: "赶上，追上", example: "I need to catch up with my work." },
  { phrase: "change one's mind", meaning: "改变主意", example: "I changed my mind about the trip." },
  { phrase: "check in", meaning: "登记入住；办理登机手续", example: "We checked in at the hotel." },
  { phrase: "check out", meaning: "结账离开；检查", example: "They checked out at noon." },
  { phrase: "cheer up", meaning: "高兴起来；振作", example: "Cheer up! Things will get better." },
  { phrase: "clean up", meaning: "清理；收拾干净", example: "Clean up your room." },
  { phrase: "clear away", meaning: "清除；收拾", example: "Clear away the dishes." },
  { phrase: "clear up", meaning: "放晴；整理；澄清", example: "The weather cleared up." },
  { phrase: "close down", meaning: "关闭；停业", example: "The factory closed down." },
  { phrase: "come about", meaning: "发生；产生", example: "How did the accident come about?" },
  { phrase: "come across", meaning: "偶然遇见；偶然发现", example: "I came across an old friend." },
  { phrase: "come along", meaning: "一起来；进步；出现", example: "How's your work coming along?" },
  { phrase: "come into being", meaning: "形成，产生", example: "When did the universe come into being?" },
  { phrase: "come into effect", meaning: "生效", example: "The new law comes into effect next month." },
  { phrase: "come off", meaning: "脱落；举行；成功", example: "The button came off." },
  { phrase: "come on", meaning: "加油；来吧；进展", example: "Come on! You can do it!" },
  { phrase: "come out", meaning: "出版；出现；结果是", example: "When will the new book come out?" },
  { phrase: "come to", meaning: "共计；苏醒；达到", example: "The bill comes to $50." },
  { phrase: "come true", meaning: "实现，成为现实", example: "My dream came true." },
  { phrase: "come up", meaning: "走近；发生；被提出", example: "A problem has come up." },
  { phrase: "come up with", meaning: "想出，提出", example: "She came up with a great idea." },
  { phrase: "comment on", meaning: "对…发表评论", example: "He refused to comment on the issue." },
  { phrase: "compare … to", meaning: "把…比作", example: "Poets often compare love to a rose." },
  { phrase: "compare with", meaning: "与…相比较", example: "Compared with last year, sales are up." },
  { phrase: "compensate for", meaning: "补偿，弥补", example: "Nothing can compensate for the loss." },
  { phrase: "comply with", meaning: "遵守，依从", example: "Comply with the rules." },
  { phrase: "concentrate on", meaning: "集中注意力于…", example: "Concentrate on your work." },
  { phrase: "congratulate … on", meaning: "祝贺某人…", example: "I congratulated him on his success." },
  { phrase: "connect with", meaning: "与…连接；联系", example: "Can you connect me with the manager?" },
  { phrase: "conscious of", meaning: "意识到…", example: "He was conscious of his mistake." },
  { phrase: "consist of", meaning: "由…组成", example: "The team consists of five members." },
  { phrase: "contribute to", meaning: "有助于；捐献；为…做贡献", example: "Exercise contributes to good health." },
  { phrase: "cool down", meaning: "冷却；平静下来", example: "Let the engine cool down." },
  { phrase: "cope with", meaning: "应付，处理", example: "How do you cope with stress?" },
  { phrase: "correspond to", meaning: "相当于；符合", example: "The American Senate corresponds to the British House of Lords." },
  { phrase: "count in", meaning: "把…算在内", example: "Count me in for the trip." },
  { phrase: "count on", meaning: "依靠；指望", example: "You can count on me." },
  { phrase: "cover up", meaning: "掩盖；包住", example: "He tried to cover up the mistake." },
  { phrase: "cross out", meaning: "划掉，删去", example: "Cross out the wrong answer." },
  { phrase: "cry out", meaning: "大声喊叫；迫切需要", example: "He cried out in pain." },
  { phrase: "cut across", meaning: "抄近路穿过；超越", example: "We cut across the field." },
  { phrase: "cut back", meaning: "削减；修剪", example: "We must cut back on expenses." },
  { phrase: "cut down", meaning: "削减；砍倒", example: "We need to cut down expenses." },
  { phrase: "cut in", meaning: "插嘴；超车插队", example: "Don't cut in while others are speaking." },
  { phrase: "cut off", meaning: "切断；中断；隔离", example: "The power was cut off." },
  { phrase: "cut short", meaning: "缩短；打断", example: "His career was cut short by illness." },
  { phrase: "date back to", meaning: "追溯到", example: "The castle dates back to the 12th century." },
  { phrase: "day after day", meaning: "日复一日", example: "Day after day, he practiced the piano." },
  { phrase: "deal in", meaning: "经营，买卖", example: "He deals in antiques." },
  { phrase: "deal with", meaning: "处理；应对；与…打交道", example: "How do you deal with stress?" },
  { phrase: "decide on", meaning: "决定，选定", example: "We haven't decided on a date yet." },
  { phrase: "dedicate … to", meaning: "把…奉献给；致力于", example: "She dedicated her life to helping others." },
  { phrase: "depend on", meaning: "依赖；取决于", example: "Whether we go depends on the weather." },
  { phrase: "deprive … of", meaning: "剥夺，使丧失", example: "They deprived him of his rights." },
  { phrase: "derive from", meaning: "起源于；从…中得到", example: "The word derives from Latin." },
  { phrase: "devote … to", meaning: "把…奉献给；致力于", example: "She devoted her life to helping others." },
  { phrase: "die down", meaning: "逐渐减弱；平息", example: "The wind died down." },
  { phrase: "die of", meaning: "死于（疾病、饥饿等）", example: "He died of cancer." },
  { phrase: "die out", meaning: "灭绝；逐渐消失", example: "Many species have died out." },
  { phrase: "differ from", meaning: "与…不同", example: "This car differs from that one." },
  { phrase: "dig into", meaning: "钻研；开始吃", example: "Dig into your new project." },
  { phrase: "distinguish … from", meaning: "区分…和…", example: "Can you distinguish a frog from a toad?" },
  { phrase: "divide … into", meaning: "把…分成", example: "Divide the cake into six pieces." },
  { phrase: "do away with", meaning: "废除，去掉", example: "We should do away with outdated rules." },
  { phrase: "do one’s best", meaning: "尽力", example: "I'll do my best to help." },
  { phrase: "do up", meaning: "修缮；包扎；扣好", example: "Do up your buttons." },
  { phrase: "do without", meaning: "没有…也行", example: "I can't do without my phone." },
  { phrase: "draw back", meaning: "退缩；收回", example: "He drew back from the edge." },
  { phrase: "draw in", meaning: "(白天)渐短；到站", example: "The train drew in to the station." },
  { phrase: "draw on", meaning: "利用；临近", example: "He drew on his savings to buy the house." },
  { phrase: "draw up", meaning: "起草；拟订", example: "They drew up a new contract." },
  { phrase: "dream of", meaning: "梦想；向往", example: "I dream of becoming a pilot." },
  { phrase: "dress up", meaning: "盛装打扮；乔装", example: "Let's dress up for the party." },
  { phrase: "drink up", meaning: "喝完", example: "Drink up your milk." },
  { phrase: "drive off", meaning: "赶走；驶离", example: "The sheep were driven off." },
  { phrase: "drop in", meaning: "顺便走访", example: "Please drop in when you're free." },
  { phrase: "drop out", meaning: "退出；辍学", example: "He dropped out of college." },
  { phrase: "dry up", meaning: "干涸；住口", example: "The lake dried up last summer." },
  { phrase: "due to", meaning: "由于，因为", example: "The delay was due to bad weather." },
  { phrase: "dwell on", meaning: "凝思；详述", example: "Don't dwell on the past." },
  { phrase: "each other", meaning: "互相", example: "We help each other." },
  { phrase: "eat up", meaning: "吃光；耗尽", example: "Eat up your vegetables." },
  { phrase: "end up", meaning: "结束；告终", example: "He ended up in prison." },
  { phrase: "engage in", meaning: "从事，参加", example: "They engaged in a heated debate." },
  { phrase: "enjoy oneself", meaning: "过得愉快", example: "Did you enjoy yourself at the party?" },
  { phrase: "enter into", meaning: "开始；参与；构成", example: "We entered into negotiations." },
  { phrase: "escape from", meaning: "从…逃离", example: "He escaped from prison." },
  { phrase: "even if / even though", meaning: "即使，虽然", example: "Even if it rains, I'll go." },
  { phrase: "ever since", meaning: "自从；从那时起", example: "Ever since we met, I've been happy." },
  { phrase: "every now and then", meaning: "时而，偶尔", example: "He calls me every now and then." },
  { phrase: "every other", meaning: "每隔一个", example: "I visit my parents every other weekend." },
  { phrase: "except for", meaning: "除了…以外", example: "The room is empty except for a table." },
  { phrase: "expose … to", meaning: "使…接触；使…暴露于", example: "Don't expose your skin to the sun too long." },
  { phrase: "face to face", meaning: "面对面", example: "We need to talk face to face." },
  { phrase: "fall back", meaning: "后退；撤退", example: "The enemy fell back." },
  { phrase: "fall behind", meaning: "落后；跟不上", example: "Don't fall behind in your studies." },
  { phrase: "fall in love with", meaning: "爱上…", example: "He fell in love with Paris." },
  { phrase: "fall off", meaning: "减少；跌落", example: "Sales fell off last quarter." },
  { phrase: "fall out", meaning: "争吵；脱落；结果是", example: "They fell out over money." },
  { phrase: "fall through", meaning: "失败；落空", example: "Our plans fell through." },
  { phrase: "far from", meaning: "远离；完全不", example: "The result is far from perfect." },
  { phrase: "feel at home", meaning: "感到自在", example: "Make yourself feel at home." },
  { phrase: "feel like", meaning: "想要；感觉像", example: "I feel like a cup of tea." },
  { phrase: "fight back", meaning: "反击；忍住", example: "She fought back her tears." },
  { phrase: "figure out", meaning: "理解；弄清楚；计算出", example: "I can't figure out this problem." },
  { phrase: "fill in", meaning: "填写；临时替代", example: "Please fill in this form." },
  { phrase: "fill out", meaning: "填写；长胖", example: "Fill out this application form." },
  { phrase: "find fault with", meaning: "挑…的毛病", example: "He always finds fault with my work." },
  { phrase: "find out", meaning: "查明，发现", example: "We need to find out the truth." },
  { phrase: "first of all", meaning: "首先", example: "First of all, let me introduce myself." },
  { phrase: "fit in", meaning: "适应；适合；合得来", example: "I don't fit in here." },
  { phrase: "fix up", meaning: "修理；安排；解决", example: "Can you fix up the broken chair?" },
  { phrase: "follow up", meaning: "跟进；追查", example: "We need to follow up on that idea." },
  { phrase: "for ever", meaning: "永远；总是", example: "I'll remember this for ever." },
  { phrase: "for example", meaning: "例如", example: "Many fruits, for example, oranges and apples, are healthy." },
  { phrase: "for free", meaning: "免费", example: "I got this sample for free." },
  { phrase: "for good", meaning: "永久地，一劳永逸地", example: "He left the town for good." },
  { phrase: "for instance", meaning: "例如，比如", example: "Take, for instance, the case of Tom." },
  { phrase: "for nothing", meaning: "免费；徒劳", example: "All that work for nothing!" },
  { phrase: "for short", meaning: "简称，缩写", example: "The United Nations, or UN for short." },
  { phrase: "for the better", meaning: "好转，向好的方向发展", example: "Things changed for the better." },
  { phrase: "for the moment", meaning: "暂时，目前", example: "I'm busy for the moment." },
  { phrase: "for the present", meaning: "暂时", example: "That's enough for the present." },
  { phrase: "for the sake of", meaning: "为了…", example: "For the sake of peace, I agreed." },
  { phrase: "for the time being", meaning: "暂时，眼下", example: "That's enough for the time being." },
  { phrase: "free from", meaning: "没有…的；不受…影响的", example: "Keep the wound free from infection." },
  { phrase: "from bad to worse", meaning: "越来越糟", example: "Things went from bad to worse." },
  { phrase: "from door to door", meaning: "挨家挨户", example: "He sold magazines from door to door." },
  { phrase: "from now on", meaning: "从现在起", example: "I'll work harder from now on." },
  { phrase: "from then on", meaning: "从那时起", example: "From then on, he studied hard." },
  { phrase: "from time to time", meaning: "不时，偶尔", example: "We meet from time to time." },
  { phrase: "gain weight", meaning: "体重增加", example: "I'm gaining weight." },
  { phrase: "gather up", meaning: "收集；概括", example: "Gather up your belongings." },
  { phrase: "generally speaking", meaning: "一般说来", example: "Generally speaking, men are taller than women." },
  { phrase: "get about", meaning: "四处走动；传播", example: "News got about quickly." },
  { phrase: "get across", meaning: "使了解；通过；讲清楚", example: "I couldn't get my point across." },
  { phrase: "get along with", meaning: "与…相处；进展", example: "She gets along well with everyone." },
  { phrase: "get at", meaning: "够得着；意指；查明", example: "What are you getting at?" },
  { phrase: "get away", meaning: "离开；逃脱", example: "The thief got away." },
  { phrase: "get back", meaning: "回来；恢复；取回", example: "Get back to work!" },
  { phrase: "get down", meaning: "下来；使沮丧；写下", example: "The rain got me down." },
  { phrase: "get down to", meaning: "开始认真做", example: "Let's get down to business." },
  { phrase: "get hold of", meaning: "获得；找到", example: "Where can I get hold of a taxi?" },
  { phrase: "get in", meaning: "进入；到达；收割", example: "The train gets in at noon." },
  { phrase: "get in the way", meaning: "挡道；妨碍", example: "Don't let fear get in the way." },
  { phrase: "get into", meaning: "进入；陷入；染上（习惯）", example: "Don't get into trouble." },
  { phrase: "get off", meaning: "下车；离开；脱下", example: "Get off the bus at the next stop." },
  { phrase: "get on", meaning: "上车；进展；相处", example: "Get on the bus." },
  { phrase: "get out", meaning: "离开；泄露；出版", example: "Get out of my room!" },
  { phrase: "get over", meaning: "克服；恢复；从…中走出来", example: "I need to get over my fear." },
  { phrase: "get ready", meaning: "准备好", example: "Get ready for school." },
  { phrase: "get rid of", meaning: "摆脱，除去", example: "I can't get rid of this cold." },
  { phrase: "get through", meaning: "完成；通过（考试）；接通电话", example: "I finally got through the exam." },
  { phrase: "get together", meaning: "聚会；收集", example: "Let's get together for a meal." },
  { phrase: "get up", meaning: "起床；站起身", example: "I get up at seven." },
  { phrase: "give away", meaning: "赠送；泄露", example: "She gave away all her old clothes." },
  { phrase: "give back", meaning: "归还；恢复", example: "Give me back my book." },
  { phrase: "give in", meaning: "屈服；让步", example: "Don't give in to pressure." },
  { phrase: "give off", meaning: "发出，放出（光、热、气味等）", example: "The fire gives off heat." },
  { phrase: "give out", meaning: "分发；用完；耗尽", example: "My money gave out." },
  { phrase: "give rise to", meaning: "引起，导致", example: "The accident gave rise to a public outcry." },
  { phrase: "give up", meaning: "放弃；戒除", example: "Never give up your dreams." },
  { phrase: "give way", meaning: "让路；让步；垮掉", example: "He refused to give way." },
  { phrase: "go about", meaning: "着手做；四处走动", example: "Go about your business." },
  { phrase: "go after", meaning: "追求；追赶", example: "Go after your dreams." },
  { phrase: "go against", meaning: "违反；对…不利", example: "Go against the rules." },
  { phrase: "go ahead", meaning: "前进；继续；做吧", example: "Go ahead, don't wait." },
  { phrase: "go by", meaning: "(时间)过去；依照", example: "Don't let this chance go by." },
  { phrase: "go down", meaning: "下降；下沉；被接受", example: "Prices went down." },
  { phrase: "go for", meaning: "去取；喜欢；适用于", example: "I'll go for a walk." },
  { phrase: "go in for", meaning: "参加；从事；爱好", example: "He goes in for swimming." },
  { phrase: "go into", meaning: "进入；调查研究；从事", example: "Let's go into the details." },
  { phrase: "go off", meaning: "爆炸；响起；离开", example: "The alarm went off at six." },
  { phrase: "go on", meaning: "继续；发生；进行", example: "What's going on?" },
  { phrase: "go on with", meaning: "继续做", example: "Go on with your work." },
  { phrase: "go out", meaning: "外出；熄灭；过时", example: "The fire went out." },
  { phrase: "go out of one's way", meaning: "特地，不怕麻烦", example: "He went out of his way to help me." },
  { phrase: "go over", meaning: "仔细检查；复习", example: "Let's go over the plan." },
  { phrase: "go round", meaning: "足够分配；流传", example: "Is there enough food to go round?" },
  { phrase: "go through", meaning: "经历；仔细检查；穿过", example: "He went through a difficult time." },
  { phrase: "go through with", meaning: "完成，把…进行到底", example: "We must go through with the plan." },
  { phrase: "go up", meaning: "上升；上涨；被建造", example: "Prices are going up." },
  { phrase: "go without", meaning: "没有…也将就", example: "We can't go without water." },
  { phrase: "grow up", meaning: "长大；成熟", example: "When I grow up, I want to be a doctor." },
  { phrase: "guard against", meaning: "提防，预防", example: "Guard against fire." },
  { phrase: "had better", meaning: "最好…", example: "You'd better go now." },
  { phrase: "had rather", meaning: "宁愿…", example: "I had rather stay home." },
  { phrase: "hand down", meaning: "把…传下来；宣布", example: "This tradition was handed down for generations." },
  { phrase: "hand in", meaning: "上交", example: "Hand in your homework." },
  { phrase: "hand out", meaning: "分发；施舍", example: "The teacher handed out worksheets." },
  { phrase: "hand over", meaning: "移交；交出", example: "Hand over the keys." },
  { phrase: "hang about", meaning: "闲荡；等待", example: "Don't hang about here." },
  { phrase: "hang on", meaning: "坚持下去；抓住；别挂断", example: "Hang on a minute!" },
  { phrase: "hang up", meaning: "挂断电话；悬挂", example: "He hung up on me." },
  { phrase: "happen to", meaning: "发生于；碰巧", example: "I happened to see him." },
  { phrase: "have an advantage over", meaning: "胜过，优于", example: "She has an advantage over the other candidates." },
  { phrase: "have difficulty (in) doing", meaning: "做…有困难", example: "I have difficulty sleeping." },
  { phrase: "have fun", meaning: "玩得高兴", example: "Have fun at the party!" },
  { phrase: "have got", meaning: "拥有；必须", example: "Have you got a pen?" },
  { phrase: "have nothing to do with", meaning: "与…无关", example: "That has nothing to do with me." },
  { phrase: "head for", meaning: "朝…方向走；注定要", example: "Let's head for the beach." },
  { phrase: "hear about", meaning: "听说；得知", example: "I've never heard about that." },
  { phrase: "hear from", meaning: "收到…的信/消息", example: "I look forward to hearing from you." },
  { phrase: "hear of", meaning: "听说；同意", example: "I won't hear of such a thing." },
  { phrase: "help oneself", meaning: "自取所需；请随意", example: "Help yourself to some cake." },
  { phrase: "help out", meaning: "帮助解决困难", example: "Can you help me out?" },
  { phrase: "hit on", meaning: "偶然发现；想到", example: "He hit on a brilliant idea." },
  { phrase: "hold back", meaning: "阻止；抑制；隐瞒", example: "She couldn't hold back her tears." },
  { phrase: "hold down", meaning: "压制；保住（工作等）", example: "He can't hold down a job." },
  { phrase: "hold off", meaning: "推迟；抵挡", example: "We held off the attack." },
  { phrase: "hold on", meaning: "等一下；坚持住；别挂断", example: "Hold on a minute!" },
  { phrase: "hold out", meaning: "伸出；坚持；维持", example: "Hold out your hand." },
  { phrase: "hold up", meaning: "举起；支撑；耽搁", example: "We were held up in traffic." },
  { phrase: "hope for", meaning: "希望；期待", example: "We are hoping for the best." },
  { phrase: "how come", meaning: "怎么会…？为什么…？", example: "How come you are late?" },
  { phrase: "hunt for", meaning: "搜寻；寻找", example: "He's hunting for a job." },
  { phrase: "hurry up", meaning: "(使)赶快", example: "Hurry up, or we'll be late." },
  { phrase: "in a hurry", meaning: "匆忙地；急于", example: "She left in a hurry." },
  { phrase: "in a moment", meaning: "立刻，马上", example: "I'll be back in a moment." },
  { phrase: "in a sense", meaning: "在某种意义上", example: "In a sense, you are right." },
  { phrase: "in a word", meaning: "总而言之", example: "In a word, I like it." },
  { phrase: "in accordance with", meaning: "根据；与…一致", example: "In accordance with your request, we have refunded the money." },
  { phrase: "in addition", meaning: "此外，而且", example: "In addition, we need more staff." },
  { phrase: "in addition to", meaning: "除…之外（还）", example: "In addition to English, he speaks French." },
  { phrase: "in advance", meaning: "提前，预先", example: "Book your tickets in advance." },
  { phrase: "in all", meaning: "总共，合计", example: "We were ten in all." },
  { phrase: "in any case", meaning: "无论如何，总之", example: "In any case, I'll go." },
  { phrase: "in brief", meaning: "简而言之", example: "In brief, the plan failed." },
  { phrase: "in business", meaning: "经商；开始工作", example: "Let's get down to business." },
  { phrase: "in case", meaning: "以防；万一", example: "Take an umbrella in case it rains." },
  { phrase: "in case of", meaning: "假如，万一", example: "In case of fire, break the glass." },
  { phrase: "in charge of", meaning: "负责；主管", example: "Who is in charge of this project?" },
  { phrase: "in common", meaning: "共同的，共有的", example: "We have a lot in common." },
  { phrase: "in common with", meaning: "与…有共同之处", example: "In common with most teenagers, she loves music." },
  { phrase: "in comparison with", meaning: "与…比较", example: "In comparison with last year, we improved." },
  { phrase: "in conclusion", meaning: "最后，总之", example: "In conclusion, I'd like to thank everyone." },
  { phrase: "in confidence", meaning: "私下地，秘密地", example: "She told me in confidence." },
  { phrase: "in consequence", meaning: "结果，因此", example: "He was late, and in consequence he missed the flight." },
  { phrase: "in control of", meaning: "控制；管理", example: "He is in control of the project." },
  { phrase: "in danger", meaning: "在危险中", example: "His life is in danger." },
  { phrase: "in debt", meaning: "欠债", example: "He is in debt to the bank." },
  { phrase: "in demand", meaning: "需求大；受欢迎", example: "Skilled workers are in demand." },
  { phrase: "in depth", meaning: "深入地", example: "We discussed the problem in depth." },
  { phrase: "in despair", meaning: "绝望地", example: "He gave up in despair." },
  { phrase: "in detail", meaning: "详细地", example: "Tell me the story in detail." },
  { phrase: "in disguise", meaning: "伪装的；假扮的", example: "He went to the party in disguise." },
  { phrase: "in effect", meaning: "实际上；生效", example: "The new law is now in effect." },
  { phrase: "in exchange for", meaning: "交换", example: "I gave her a pen in exchange for a pencil." },
  { phrase: "in existence", meaning: "存在的；现存的", example: "This is the oldest temple in existence." },
  { phrase: "in favor of", meaning: "支持；有利于", example: "I'm in favor of the proposal." },
  { phrase: "in force", meaning: "有效；大批地", example: "The new rules will soon be in force." },
  { phrase: "in front of", meaning: "在…前面", example: "The bus stops in front of the school." },
  { phrase: "in future", meaning: "今后，以后", example: "In future, be more careful." },
  { phrase: "in general", meaning: "通常；大体上", example: "In general, people are friendly." },
  { phrase: "in good condition", meaning: "状况良好", example: "The car is in good condition." },
  { phrase: "in hand", meaning: "在手头；处理中；控制中", example: "The situation is in hand." },
  { phrase: "in harmony with", meaning: "与…协调一致", example: "Live in harmony with nature." },
  { phrase: "in haste", meaning: "匆忙地", example: "He left in haste." },
  { phrase: "in honour of", meaning: "为纪念；为庆祝", example: "A banquet was held in honour of the president." },
  { phrase: "in hopes of", meaning: "怀着…的希望", example: "He went to the city in hopes of finding work." },
  { phrase: "in itself", meaning: "本质上；就其本身而言", example: "The idea is good in itself." },
  { phrase: "in line", meaning: "成一直线；排队；协调", example: "Stand in line." },
  { phrase: "in memory of", meaning: "纪念…", example: "A statue was erected in memory of the hero." },
  { phrase: "in nature", meaning: "本质上；在自然界中", example: "The problem is political in nature." },
  { phrase: "in need of", meaning: "需要…", example: "The house is in need of repair." },
  { phrase: "in no case", meaning: "决不", example: "In no case should you lie." },
  { phrase: "in no time", meaning: "立刻，马上", example: "I'll be back in no time." },
  { phrase: "in one's opinion", meaning: "在某人看来", example: "In my opinion, it's wrong." },
  { phrase: "in one's power", meaning: "在某人能力范围内", example: "I'll do everything in my power to help." },
  { phrase: "in operation", meaning: "运行中；实施中", example: "The new system is now in operation." },
  { phrase: "in order", meaning: "整齐；有秩序；妥当", example: "Put the files in order." },
  { phrase: "in order to", meaning: "为了，以便", example: "She studied hard in order to pass." },
  { phrase: "in other words", meaning: "换句话说", example: "In other words, you failed." },
  { phrase: "in part", meaning: "部分地", example: "The accident was in part due to the weather." },
  { phrase: "in particular", meaning: "特别，尤其", example: "I like this one in particular." },
  { phrase: "in peace", meaning: "平静地；和睦地", example: "Leave me in peace." },
  { phrase: "in person", meaning: "亲自；本人", example: "Come and see me in person." },
  { phrase: "in place", meaning: "在适当的位置；就位", example: "Everything is in place." },
  { phrase: "in place of", meaning: "代替", example: "Use honey in place of sugar." },
  { phrase: "in plenty", meaning: "充足，丰富", example: "There is food in plenty." },
  { phrase: "in possession of", meaning: "拥有；占有", example: "He is in possession of a large fortune." },
  { phrase: "in practice", meaning: "在实践中；实际上", example: "The idea works well in practice." },
  { phrase: "in praise of", meaning: "赞美…", example: "He wrote a poem in praise of her beauty." },
  { phrase: "in principle", meaning: "原则上；大体上", example: "I agree in principle." },
  { phrase: "in private", meaning: "私下地", example: "May I speak to you in private?" },
  { phrase: "in progress", meaning: "在进行中", example: "The work is in progress." },
  { phrase: "in proportion to", meaning: "与…成比例", example: "The size of the box is in proportion to the contents." },
  { phrase: "in public", meaning: "公开地", example: "He doesn't like to speak in public." },
  { phrase: "in pursuit of", meaning: "追求；追赶", example: "They were in pursuit of the thief." },
  { phrase: "in question", meaning: "正在谈论的；有疑问的", example: "The person in question has left the country." },
  { phrase: "in reality", meaning: "实际上，事实上", example: "In reality, things are different." },
  { phrase: "in regard to", meaning: "关于", example: "In regard to your letter, I'm pleased to reply." },
  { phrase: "in relation to", meaning: "关于；与…相比", example: "Prices are low in relation to quality." },
  { phrase: "in return for", meaning: "作为对…的回报", example: "He gave me a gift in return for my help." },
  { phrase: "in ruins", meaning: "成为废墟；破败不堪", example: "The castle lies in ruins." },
  { phrase: "in safety", meaning: "安全地", example: "The children are now in safety." },
  { phrase: "in season", meaning: "应时的；在旺季", example: "Fruit is cheaper in season." },
  { phrase: "in secret", meaning: "秘密地", example: "They met in secret." },
  { phrase: "in shape", meaning: "处于良好状态；体型好", example: "I need to get in shape." },
  { phrase: "in sight", meaning: "看得见；在望", example: "The end is in sight." },
  { phrase: "in silence", meaning: "沉默地", example: "They sat in silence." },
  { phrase: "in spite of", meaning: "尽管", example: "In spite of the rain, we went out." },
  { phrase: "in step", meaning: "步调一致；同步", example: "Keep in step with the music." },
  { phrase: "in store", meaning: "储备着；即将发生", example: "There's a surprise in store for you." },
  { phrase: "in sum", meaning: "总而言之", example: "In sum, it was a great success." },
  { phrase: "in support of", meaning: "支持", example: "He spoke in support of the motion." },
  { phrase: "in terms of", meaning: "就…而言；用…的话", example: "In terms of money, we are okay." },
  { phrase: "in the air", meaning: "在空中；流传；未定", example: "Our plans are still in the air." },
  { phrase: "in the dark", meaning: "在黑暗中；不知道", example: "I was kept in the dark about the decision." },
  { phrase: "in the distance", meaning: "在远处", example: "We saw a light in the distance." },
  { phrase: "in the end", meaning: "最后，终于", example: "In the end, he succeeded." },
  { phrase: "in the event of", meaning: "如果…发生", example: "In the event of fire, use the stairs." },
  { phrase: "in the first place", meaning: "首先；一开始", example: "Why did you come here in the first place?" },
  { phrase: "in the form of", meaning: "以…的形式", example: "Help came in the form of a loan." },
  { phrase: "in the habit of", meaning: "有…的习惯", example: "He's in the habit of smoking after meals." },
  { phrase: "in the interests of", meaning: "为了…的利益", example: "In the interests of safety, we moved." },
  { phrase: "in the long run", meaning: "从长远看", example: "Exercise pays off in the long run." },
  { phrase: "in the meantime", meaning: "在此期间", example: "We'll wait; in the meantime, have some tea." },
  { phrase: "in the midst of", meaning: "在…之中", example: "In the midst of the crowd, I lost her." },
  { phrase: "in the name of", meaning: "以…的名义", example: "Stop in the name of the law!" },
  { phrase: "in the near future", meaning: "在不久的将来", example: "We'll visit you in the near future." },
  { phrase: "in the open air", meaning: "在户外", example: "Let's eat in the open air." },
  { phrase: "in the past", meaning: "在过去", example: "In the past, people used candles." },
  { phrase: "in the process of", meaning: "在…的过程中", example: "The bridge is in the process of construction." },
  { phrase: "in the right", meaning: "正确；有理", example: "You are in the right." },
  { phrase: "in the world", meaning: "究竟，到底", example: "What in the world are you doing?" },
  { phrase: "in theory", meaning: "理论上", example: "In theory, it should work." },
  { phrase: "in time", meaning: "及时；最终", example: "You'll learn in time." },
  { phrase: "in touch", meaning: "联系；接触", example: "Keep in touch!" },
  { phrase: "in trouble", meaning: "处于困境中", example: "He's in trouble with the police." },
  { phrase: "in truth", meaning: "事实上，的确", example: "In truth, I didn't want to go." },
  { phrase: "in turn", meaning: "依次；反过来", example: "Each student speaks in turn." },
  { phrase: "in use", meaning: "在使用中", example: "The printer is in use." },
  { phrase: "in vain", meaning: "徒劳地", example: "We tried, but in vain." },
  { phrase: "in view of", meaning: "鉴于，考虑到", example: "In view of the weather, we cancelled the picnic." },
  { phrase: "in want of", meaning: "需要", example: "The car is in want of repair." },
  { phrase: "in the way of", meaning: "在…方面；妨碍", example: "He stood in the way of progress." },
  { phrase: "junior to", meaning: "比…年少；低于", example: "He is junior to me by two years." },
  { phrase: "just about", meaning: "几乎，差不多", example: "I've just about finished." },
  { phrase: "keep an eye on", meaning: "照看；留意", example: "Keep an eye on the baby." },
  { phrase: "keep back", meaning: "阻止；隐瞒；忍住", example: "She kept back the tears." },
  { phrase: "keep company", meaning: "陪伴；交往", example: "Keep company with good people." },
  { phrase: "keep down", meaning: "控制；镇压；放低", example: "Keep down expenses." },
  { phrase: "keep from", meaning: "阻止；忍住不做", example: "I couldn't keep from laughing." },
  { phrase: "keep in mind", meaning: "记住", example: "Keep in mind that he is a child." },
  { phrase: "keep off", meaning: "让开；不接近", example: "Keep off the grass." },
  { phrase: "keep on", meaning: "继续（做某事）；坚持", example: "Keep on trying!" },
  { phrase: "keep one's head", meaning: "保持冷静", example: "Keep your head in an emergency." },
  { phrase: "keep one's word", meaning: "守信", example: "He always keeps his word." },
  { phrase: "keep pace with", meaning: "与…齐步前进", example: "Wages must keep pace with inflation." },
  { phrase: "keep to", meaning: "遵守；坚持", example: "Keep to the speed limit." },
  { phrase: "keep track of", meaning: "记录；掌握…的线索", example: "Keep track of your expenses." },
  { phrase: "keep up", meaning: "保持；继续", example: "Keep up the good work!" },
  { phrase: "keep up with", meaning: "跟上；不落后；保持联系", example: "I try to keep up with the news." },
  { phrase: "key up", meaning: "使紧张；使兴奋", example: "The players were keyed up for the game." },
  { phrase: "kick off", meaning: "开始；踢掉", example: "The game kicks off at 3 pm." },
  { phrase: "kind of", meaning: "有点，有几分", example: "I'm kind of tired." },
  { phrase: "knock down", meaning: "击倒；拆除；降价", example: "The old building was knocked down." },
  { phrase: "knock off", meaning: "下班；停止；减价", example: "What time do you knock off?" },
  { phrase: "knock out", meaning: "击倒；淘汰；使筋疲力尽", example: "The boxer was knocked out in the first round." },
  { phrase: "know about", meaning: "了解；知道…的情况", example: "Do you know about the Internet?" },
  { phrase: "know better than", meaning: "很明白而不至于…", example: "You should know better than to trust him." },
  { phrase: "known as", meaning: "被称为，以…闻名", example: "He is known as a great writer." },
  { phrase: "lack of", meaning: "缺乏", example: "Lack of sleep is bad for health." },
  { phrase: "laugh at", meaning: "嘲笑；因…而发笑", example: "Don't laugh at others." },
  { phrase: "lay aside", meaning: "把…放在一边；积蓄", example: "Lay aside some money for the future." },
  { phrase: "lay down", meaning: "放下；规定；牺牲", example: "Lay down your weapons." },
  { phrase: "lay off", meaning: "解雇；停止", example: "The factory laid off 500 workers." },
  { phrase: "lay out", meaning: "布置；设计；花费", example: "The garden is beautifully laid out." },
  { phrase: "lead the way", meaning: "带路；示范", example: "You lead the way." },
  { phrase: "lead to", meaning: "导致；通向", example: "Hard work leads to success." },
  { phrase: "lean on", meaning: "依靠；靠在…上", example: "Lean on me if you're tired." },
  { phrase: "learn about", meaning: "了解；学习", example: "We learned about the accident." },
  { phrase: "learn by heart", meaning: "记住，背熟", example: "Learn the poem by heart." },
  { phrase: "leave alone", meaning: "不打扰；让独自待着", example: "Leave me alone!" },
  { phrase: "leave behind", meaning: "留下；遗忘；超过", example: "Don't leave your bag behind." },
  { phrase: "leave for", meaning: "动身前往", example: "He left for Beijing yesterday." },
  { phrase: "leave off", meaning: "停止；中断", example: "Leave off biting your nails." },
  { phrase: "leave out", meaning: "省略；遗漏", example: "You've left out a word." },
  { phrase: "let alone", meaning: "更不用说；不打扰", example: "He can't walk, let alone run." },
  { phrase: "let down", meaning: "放下；使失望", example: "I won't let you down." },
  { phrase: "let go", meaning: "放开；释放", example: "Let go of my hand." },
  { phrase: "let in", meaning: "让…进入；放进", example: "Let in some fresh air." },
  { phrase: "let off", meaning: "排放；放过；宽恕", example: "They let him off with a warning." },
  { phrase: "let out", meaning: "释放；发出（声音）；泄露", example: "He let out a scream." },
  { phrase: "lie in", meaning: "在于；睡懒觉", example: "The problem lies in the engine." },
  { phrase: "light up", meaning: "点燃；照亮；容光焕发", example: "Her face lit up when she saw him." },
  { phrase: "line up", meaning: "排队；列队", example: "People were lining up for tickets." },
  { phrase: "listen to", meaning: "听…；听从", example: "Listen to me!" },
  { phrase: "little by little", meaning: "逐渐地；一点一点地", example: "Little by little, he improved." },
  { phrase: "live by", meaning: "靠…为生", example: "He lives by fishing." },
  { phrase: "live on", meaning: "以…为主食；靠…生活；继续存在", example: "They live on rice." },
  { phrase: "live through", meaning: "度过；经受住", example: "He lived through two world wars." },
  { phrase: "live up to", meaning: "不辜负；达到", example: "He failed to live up to his promise." },
  { phrase: "lock up", meaning: "锁好；监禁", example: "Lock up before you go." },
  { phrase: "long for", meaning: "渴望；向往", example: "She longed for a rest." },
  { phrase: "look about", meaning: "四下环顾；察看", example: "He looked about the room." },
  { phrase: "look after", meaning: "照顾；照料", example: "Can you look after my cat?" },
  { phrase: "look back", meaning: "回顾；回头看", example: "Don't look back." },
  { phrase: "look down on / upon", meaning: "看不起，轻视", example: "Don't look down upon the poor." },
  { phrase: "look for", meaning: "寻找", example: "I'm looking for my phone." },
  { phrase: "look forward to", meaning: "期待，盼望", example: "I look forward to meeting you." },
  { phrase: "look in", meaning: "顺便看望；朝里面看", example: "I'll look in on you later." },
  { phrase: "look into", meaning: "调查；研究", example: "The police are looking into the case." },
  { phrase: "look like", meaning: "看起来像", example: "You look like your mother." },
  { phrase: "look on", meaning: "旁观；看待", example: "Passers-by just looked on." },
  { phrase: "look out", meaning: "留神；小心", example: "Look out for cars!" },
  { phrase: "look over", meaning: "检查；查看", example: "Look over the report." },
  { phrase: "look through", meaning: "浏览；看穿", example: "Look through the window." },
  { phrase: "look up", meaning: "查阅；仰望；好转", example: "Look up the word in a dictionary." },
  { phrase: "look up to", meaning: "尊敬", example: "I look up to my father." },
  { phrase: "lose face", meaning: "丢脸", example: "He was afraid of losing face." },
  { phrase: "lose heart", meaning: "丧失信心；灰心", example: "Don't lose heart!" },
  { phrase: "lose one's temper", meaning: "发脾气", example: "He lost his temper." },
  { phrase: "lose one's way", meaning: "迷路", example: "I lost my way in the forest." },
  { phrase: "lose sight of", meaning: "看不见；忽略", example: "Never lose sight of your goal." },
  { phrase: "lose weight", meaning: "减肥", example: "I need to lose weight." },
  { phrase: "major in", meaning: "主修", example: "She majors in English." },
  { phrase: "make a difference", meaning: "有影响；起作用", example: "Your help made a big difference." },
  { phrase: "make a face", meaning: "做鬼脸", example: "Stop making faces at me!" },
  { phrase: "make a fool of", meaning: "愚弄；出洋相", example: "Don't make a fool of yourself." },
  { phrase: "make a living", meaning: "谋生", example: "He makes a living as a painter." },
  { phrase: "make a mistake", meaning: "犯错误", example: "Everyone makes mistakes." },
  { phrase: "make a noise", meaning: "发出噪音", example: "Don't make a noise." },
  { phrase: "make an effort", meaning: "努力", example: "Make an effort to be nice." },
  { phrase: "make believe", meaning: "假装", example: "The children made believe they were pirates." },
  { phrase: "make clear", meaning: "讲清楚，表明", example: "Let me make clear my position." },
  { phrase: "make for", meaning: "走向；有助于；导致", example: "The ship made for the harbour." },
  { phrase: "make friends", meaning: "交朋友", example: "It's easy to make friends here." },
  { phrase: "make fun of", meaning: "取笑", example: "Don't make fun of him." },
  { phrase: "make one's way", meaning: "前进；成功", example: "He slowly made his way through the crowd." },
  { phrase: "make out", meaning: "辨认出；理解；填写", example: "I can't make out his handwriting." },
  { phrase: "make peace", meaning: "讲和", example: "The two countries made peace." },
  { phrase: "make progress", meaning: "取得进步", example: "You are making good progress." },
  { phrase: "make room for", meaning: "给…让出地方", example: "Make room for the old lady." },
  { phrase: "make sense", meaning: "有意义；讲得通", example: "Does that make sense?" },
  { phrase: "make sure", meaning: "确保；查明", example: "Make sure the door is locked." },
  { phrase: "make the best of", meaning: "充分利用", example: "Make the best of your time." },
  { phrase: "make the most of", meaning: "尽量利用", example: "Make the most of every opportunity." },
  { phrase: "make up", meaning: "编造；弥补；化妆；组成", example: "Girls make up half the class." },
  { phrase: "make up for", meaning: "补偿，弥补", example: "Hard work can make up for a lack of talent." },
  { phrase: "make use of", meaning: "利用", example: "Make good use of your time." },
  { phrase: "make way", meaning: "让路；前进", example: "Make way for the king!" },
  { phrase: "many a", meaning: "许多的（后接单数名词）", example: "Many a student has passed the exam." },
  { phrase: "mark down", meaning: "记下；减价", example: "Mark down the prices." },
  { phrase: "mark out", meaning: "划出；规划", example: "Mark out the boundaries." },
  { phrase: "may as well", meaning: "还不如；不妨", example: "You may as well tell me the truth." },
  { phrase: "meet with", meaning: "遭遇；偶然遇到", example: "We met with an accident." },
  { phrase: "mix up", meaning: "混淆；搅拌", example: "Don't mix up the two cases." },
  { phrase: "more or less", meaning: "或多或少", example: "It's more or less true." },
  { phrase: "move about", meaning: "走来走去；经常搬家", example: "He moved about restlessly." },
  { phrase: "move away", meaning: "搬走；离开", example: "They moved away last year." },
  { phrase: "move in", meaning: "搬进", example: "When can we move in?" },
  { phrase: "move on", meaning: "继续前进；离开", example: "Time to move on." },
  { phrase: "name after", meaning: "以…命名", example: "The bridge is named after the hero." },
  { phrase: "neither … nor", meaning: "既不…也不…", example: "Neither he nor I am right." },
  { phrase: "never mind", meaning: "不要紧；没关系", example: "Never mind, I'll do it myself." },
  { phrase: "next to", meaning: "紧挨着；几乎", example: "She sat next to me." },
  { phrase: "no doubt", meaning: "无疑地", example: "No doubt he will come." },
  { phrase: "no longer", meaning: "不再", example: "I can wait no longer." },
  { phrase: "no more than", meaning: "仅仅，只是", example: "He has no more than ten books." },
  { phrase: "no sooner … than", meaning: "一…就…", example: "No sooner had he arrived than it rained." },
  { phrase: "no wonder", meaning: "难怪", example: "No wonder you're tired." },
  { phrase: "none other than", meaning: "正是", example: "It was none other than the president." },
  { phrase: "not at all", meaning: "一点也不；别客气", example: "I don't like it at all." },
  { phrase: "not only … but also", meaning: "不仅…而且…", example: "He not only sings but also dances." },
  { phrase: "not so much … as", meaning: "与其说…不如说…", example: "He is not so much a writer as a journalist." },
  { phrase: "nothing but", meaning: "只有；只不过", example: "He is nothing but a liar." },
  { phrase: "now and then", meaning: "偶尔", example: "I see him now and then." },
  { phrase: "now that", meaning: "既然", example: "Now that you're here, let's begin." },
  { phrase: "object to", meaning: "反对", example: "I object to the plan." },
  { phrase: "occur to", meaning: "被想到", example: "It never occurred to me." },
  { phrase: "of course", meaning: "当然", example: "Of course I'll come." },
  { phrase: "off and on", meaning: "断断续续地；有时", example: "It rained off and on all day." },
  { phrase: "off duty", meaning: "下班，不当班", example: "I'm off duty today." },
  { phrase: "on a large scale", meaning: "大规模地", example: "They produce cars on a large scale." },
  { phrase: "on a small scale", meaning: "小规模地", example: "The project started on a small scale." },
  { phrase: "on account of", meaning: "因为", example: "They cancelled on account of rain." },
  { phrase: "on average", meaning: "平均；通常", example: "On average, we work 40 hours a week." },
  { phrase: "on behalf of", meaning: "代表", example: "I'm here on behalf of the team." },
  { phrase: "on board", meaning: "在船（飞机、火车）上；加入", example: "Welcome on board!" },
  { phrase: "on business", meaning: "因公", example: "He's away on business." },
  { phrase: "on condition that", meaning: "如果，在…条件下", example: "You can go, on condition that you come back early." },
  { phrase: "on duty", meaning: "值班；上班", example: "Who's on duty today?" },
  { phrase: "on earth", meaning: "究竟；在地球上", example: "What on earth is that?" },
  { phrase: "on end", meaning: "连续地；竖着", example: "It rained for days on end." },
  { phrase: "on fire", meaning: "着火；非常激动", example: "The house is on fire!" },
  { phrase: "on foot", meaning: "步行", example: "We came on foot." },
  { phrase: "on guard", meaning: "站岗；警惕", example: "Stay on guard." },
  { phrase: "on hand", meaning: "现有；在手边", example: "We have enough food on hand." },
  { phrase: "on holiday", meaning: "在度假", example: "He's on holiday." },
  { phrase: "on one's guard", meaning: "警惕；提防", example: "Be on your guard against thieves." },
  { phrase: "on one's own", meaning: "独自地；独立地", example: "She lives on her own." },
  { phrase: "on purpose", meaning: "故意地", example: "He did it on purpose." },
  { phrase: "on sale", meaning: "出售；廉价出售", example: "The house is on sale." },
  { phrase: "on schedule", meaning: "按时，如期", example: "The train arrived on schedule." },
  { phrase: "on strike", meaning: "罢工", example: "The workers are on strike." },
  { phrase: "on the air", meaning: "正在广播", example: "We're on the air in five minutes." },
  { phrase: "on the basis of", meaning: "在…基础上", example: "Decisions were made on the basis of evidence." },
  { phrase: "on the contrary", meaning: "正相反", example: "It's not boring; on the contrary, it's exciting." },
  { phrase: "on the decline", meaning: "在衰退中；在下降", example: "The economy is on the decline." },
  { phrase: "on the decrease", meaning: "在减少中", example: "Sales are on the decrease." },
  { phrase: "on the go", meaning: "忙个不停；活跃", example: "She's always on the go." },
  { phrase: "on the increase", meaning: "在增加中", example: "Crime is on the increase." },
  { phrase: "on the march", meaning: "在行军中；在进展中", example: "The army is on the march." },
  { phrase: "on the move", meaning: "在活动中；在前进", example: "The family is always on the move." },
  { phrase: "on the one hand", meaning: "一方面", example: "On the one hand, it's cheap." },
  { phrase: "on the other hand", meaning: "另一方面", example: "On the other hand, it's not very good." },
  { phrase: "on the point of", meaning: "正要…的时候", example: "She was on the point of leaving when I called." },
  { phrase: "on the rise", meaning: "在上涨；在增加", example: "House prices are on the rise." },
  { phrase: "on the road", meaning: "在旅途中", example: "We've been on the road for three hours." },
  { phrase: "on the run", meaning: "奔跑；在逃", example: "The escaped prisoner is on the run." },
  { phrase: "on the spot", meaning: "当场，立即", example: "He was arrested on the spot." },
  { phrase: "on the whole", meaning: "总的来看", example: "On the whole, I agree." },
  { phrase: "on time", meaning: "准时", example: "Come on time." },
  { phrase: "once again", meaning: "再一次", example: "Once again, you are wrong." },
  { phrase: "once in a while", meaning: "偶尔", example: "We go out once in a while." },
  { phrase: "once more", meaning: "再一次", example: "Try once more." },
  { phrase: "once upon a time", meaning: "从前", example: "Once upon a time there was a king." },
  { phrase: "one another", meaning: "互相（三者及以上）", example: "The team members help one another." },
  { phrase: "open to", meaning: "对…开放；易于", example: "The park is open to the public." },
  { phrase: "open up", meaning: "打开；开发；吐露", example: "Open up the door!" },
  { phrase: "operate on", meaning: "给…动手术", example: "The doctors operated on his heart." },
  { phrase: "or else", meaning: "否则", example: "Hurry up, or else you'll be late." },
  { phrase: "or so", meaning: "大约", example: "It costs $10 or so." },
  { phrase: "other than", meaning: "除了；不同于", example: "There's no one here other than me." },
  { phrase: "out of", meaning: "从…向外；由于；缺乏；脱离", example: "We're out of milk." },
  { phrase: "out of breath", meaning: "上气不接下气", example: "He ran so fast he was out of breath." },
  { phrase: "out of control", meaning: "失去控制", example: "The car went out of control." },
  { phrase: "out of danger", meaning: "脱离危险", example: "The patient is now out of danger." },
  { phrase: "out of date", meaning: "过时的", example: "This dictionary is out of date." },
  { phrase: "out of doors", meaning: "在户外", example: "Play out of doors." },
  { phrase: "out of fashion", meaning: "不流行", example: "Long skirts are out of fashion." },
  { phrase: "out of focus", meaning: "焦点没对准；模糊", example: "The picture is out of focus." },
  { phrase: "out of hand", meaning: "无法控制；立即", example: "The situation got out of hand." },
  { phrase: "out of line", meaning: "不成直线；不合适", example: "His behaviour was out of line." },
  { phrase: "out of luck", meaning: "运气不好", example: "You're out of luck." },
  { phrase: "out of one's mind", meaning: "发疯；精神失常", example: "Are you out of your mind?" },
  { phrase: "out of order", meaning: "出故障", example: "The lift is out of order." },
  { phrase: "out of place", meaning: "不合适；不在原来的位置", example: "His joke was out of place." },
  { phrase: "out of practice", meaning: "久不练习；荒疏", example: "I'm out of practice at the piano." },
  { phrase: "out of question", meaning: "毫无疑问", example: "His success is out of question." },
  { phrase: "out of season", meaning: "在淡季", example: "Oysters are cheaper out of season." },
  { phrase: "out of shape", meaning: "变形；身体不佳", example: "The wheel is out of shape." },
  { phrase: "out of sight", meaning: "看不见", example: "The plane flew out of sight." },
  { phrase: "out of step", meaning: "步调不一致", example: "He is out of step with the rest." },
  { phrase: "out of stock", meaning: "无现货，脱销", example: "The book is out of stock." },
  { phrase: "out of style", meaning: "过时的；不流行", example: "Those clothes are out of style." },
  { phrase: "out of the question", meaning: "不可能的", example: "Going there on foot is out of the question." },
  { phrase: "out of touch", meaning: "失去联系；不了解", example: "I'm out of touch with current affairs." },
  { phrase: "out of work", meaning: "失业", example: "He's been out of work for months." },
  { phrase: "over and over", meaning: "反复地，再三", example: "Read it over and over." },
  { phrase: "owe to", meaning: "归功于；欠", example: "I owe my success to him." },
  { phrase: "own up", meaning: "承认，坦白", example: "He owned up to his mistake." },
  { phrase: "pass away", meaning: "去世", example: "Her grandfather passed away peacefully." },
  { phrase: "pass by", meaning: "经过；忽略", example: "He passed by without a word." },
  { phrase: "pass down", meaning: "传递；流传", example: "The story was passed down for generations." },
  { phrase: "pass on", meaning: "传递；继续下去", example: "Pass on the message." },
  { phrase: "pass out", meaning: "昏倒；分发", example: "He passed out from the heat." },
  { phrase: "pass over", meaning: "忽略；省略", example: "We passed over the details." },
  { phrase: "pay attention to", meaning: "注意", example: "Pay attention to the road." },
  { phrase: "pay back", meaning: "偿还；报复", example: "I'll pay you back tomorrow." },
  { phrase: "pay for", meaning: "付款；为…付出代价", example: "You'll pay for this mistake." },
  { phrase: "pay off", meaning: "还清；取得成功", example: "His hard work paid off." },
  { phrase: "pay a visit", meaning: "访问", example: "Let's pay a visit to the museum." },
  { phrase: "persist in", meaning: "坚持", example: "He persisted in his foolish plan." },
  { phrase: "pick out", meaning: "挑选；辨认", example: "Pick out the red one." },
  { phrase: "pick up", meaning: "捡起；学会；接（人）；好转", example: "Pick up the phone." },
  { phrase: "pile up", meaning: "堆积；积累", example: "Work is piling up." },
  { phrase: "play a part in", meaning: "在…中起作用", example: "He played a part in the success." },
  { phrase: "play with", meaning: "玩弄；与…玩", example: "Don't play with fire." },
  { phrase: "point out", meaning: "指出", example: "He pointed out my mistake." },
  { phrase: "pop up", meaning: "突然出现", example: "New ideas pop up every day." },
  { phrase: "prefer … to", meaning: "喜欢…胜过…", example: "I prefer tea to coffee." },
  { phrase: "prepare for", meaning: "为…做准备", example: "Prepare for the worst." },
  { phrase: "prevent … from", meaning: "阻止…做…", example: "The rain prevented us from going out." },
  { phrase: "prior to", meaning: "在…之前", example: "Prior to the meeting, we discussed the agenda." },
  { phrase: "protect … from", meaning: "保护…不受…", example: "Protect your skin from the sun." },
  { phrase: "proud of", meaning: "以…自豪", example: "I'm proud of you." },
  { phrase: "provide … with", meaning: "给…提供…", example: "The hotel provides guests with free breakfast." },
  { phrase: "pull down", meaning: "拆毁；拉下", example: "The old building was pulled down." },
  { phrase: "pull in", meaning: "(车)进站；停下；赚钱", example: "The train pulled in on time." },
  { phrase: "pull off", meaning: "脱去；完成（困难的事）", example: "He pulled off a great victory." },
  { phrase: "pull on", meaning: "穿上；继续拉", example: "Pull on your socks." },
  { phrase: "pull out", meaning: "拔出；取出；(车)驶出", example: "He pulled out a gun." },
  { phrase: "pull up", meaning: "(使)停下；拔起", example: "The car pulled up at the gate." },
  { phrase: "put aside", meaning: "储存；撇开", example: "Put aside some money each month." },
  { phrase: "put back", meaning: "放回；推迟", example: "Put the book back on the shelf." },
  { phrase: "put down", meaning: "放下；记下；镇压", example: "Put down your name." },
  { phrase: "put forward", meaning: "提出；建议", example: "He put forward a new idea." },
  { phrase: "put in", meaning: "花费（时间等）；提出；插话", example: "He put in a lot of effort." },
  { phrase: "put into practice", meaning: "实施，实行", example: "Put the plan into practice." },
  { phrase: "put off", meaning: "推迟；使反感", example: "Don't put off your homework." },
  { phrase: "put on", meaning: "穿上；上演；增加（体重）", example: "Put on your coat." },
  { phrase: "put out", meaning: "熄灭；伸出；生产；使苦恼", example: "Put out the fire." },
  { phrase: "put through", meaning: "接通电话；完成；使经受", example: "Put me through to the manager." },
  { phrase: "put up", meaning: "建造；举起；张贴；留宿", example: "Put up a tent." },
  { phrase: "put up with", meaning: "忍受", example: "I can't put up with his rudeness." },
  { phrase: "qualify for", meaning: "有…的资格", example: "She qualified for the final." },
  { phrase: "queue up", meaning: "排队等候", example: "People queued up for tickets." },
  { phrase: "rain out", meaning: "因雨取消", example: "The game was rained out." },
  { phrase: "rather than", meaning: "而不是", example: "I'd go out rather than stay at home." },
  { phrase: "react to", meaning: "对…作出反应", example: "How did he react to the news?" },
  { phrase: "read over", meaning: "通读；审阅", example: "Read over the contract carefully." },
  { phrase: "reason with", meaning: "与…讲道理", example: "You can't reason with him." },
  { phrase: "refer to", meaning: "提到；参考；指的是", example: "This refers to the previous sentence." },
  { phrase: "refer to … as", meaning: "把…称为", example: "He is referred to as a genius." },
  { phrase: "regardless of", meaning: "不顾，不管", example: "He went regardless of the danger." },
  { phrase: "relate to", meaning: "与…有关；理解", example: "I can't relate to that problem." },
  { phrase: "relieve … of", meaning: "解除…的负担；偷走", example: "Let me relieve you of that box." },
  { phrase: "rely on", meaning: "依靠", example: "Rely on your own judgment." },
  { phrase: "remind … of", meaning: "使想起", example: "You remind me of your father." },
  { phrase: "respond to", meaning: "响应；回答", example: "He didn't respond to my question." },
  { phrase: "result from", meaning: "由…引起", example: "His illness resulted from overwork." },
  { phrase: "result in", meaning: "导致", example: "Hard work results in success." },
  { phrase: "ring off", meaning: "挂断电话", example: "He rang off before I could answer." },
  { phrase: "ring up", meaning: "打电话；记录", example: "Ring me up when you arrive." },
  { phrase: "rob … of", meaning: "抢劫…的东西；剥夺", example: "He was robbed of his wallet." },
  { phrase: "run across", meaning: "偶然遇见", example: "I ran across an old friend." },
  { phrase: "run after", meaning: "追赶；追求", example: "Run after the bus!" },
  { phrase: "run away", meaning: "逃跑", example: "Don't run away from your problems." },
  { phrase: "run down", meaning: "撞倒；说坏话；耗尽；衰退", example: "The batteries are running down." },
  { phrase: "run into", meaning: "偶然遇到；撞上；陷入", example: "We ran into trouble." },
  { phrase: "run off", meaning: "跑掉；复印；流掉", example: "The thief ran off." },
  { phrase: "run out (of)", meaning: "用完；耗尽", example: "We've run out of bread." },
  { phrase: "run over", meaning: "碾过；溢出；快速复习", example: "He was run over by a car." },
  { phrase: "run through", meaning: "贯穿；匆匆检查；浪费", example: "A thought ran through my mind." },
  { phrase: "rush hour", meaning: "交通高峰时间", example: "Avoid the rush hour." },
  { phrase: "save for", meaning: "为…储蓄；留作…用", example: "Save the best for last." },
  { phrase: "save up", meaning: "储蓄，攒钱", example: "They're saving up to buy a house." },
  { phrase: "search for", meaning: "寻找；搜索", example: "I searched for my keys." },
  { phrase: "see about", meaning: "负责处理；考虑", example: "I'll see about getting a ticket." },
  { phrase: "see … off", meaning: "为…送行", example: "We went to the station to see him off." },
  { phrase: "see to", meaning: "负责；照料", example: "See to the arrangements." },
  { phrase: "seek after", meaning: "寻找；追求", example: "She is much sought after as a speaker." },
  { phrase: "seize hold of", meaning: "抓住；占领", example: "Seize hold of the rope." },
  { phrase: "sell off", meaning: "廉价出售", example: "The store sold off all its summer stock." },
  { phrase: "sell out", meaning: "卖光；背叛", example: "The tickets were sold out." },
  { phrase: "send for", meaning: "派人去请；索取", example: "Send for a doctor!" },
  { phrase: "send in", meaning: "递送；提交", example: "Send in your application." },
  { phrase: "send off", meaning: "邮寄；送别；罚下场", example: "He was sent off for a foul." },
  { phrase: "send out", meaning: "发出；派遣；散发出", example: "Send out invitations." },
  { phrase: "serve as", meaning: "充当；起…作用", example: "This room can serve as a study." },
  { phrase: "set about", meaning: "开始做", example: "He set about cleaning the house." },
  { phrase: "set against", meaning: "使对立；使抵消", example: "Set one against the other." },
  { phrase: "set aside", meaning: "留出；拨出；把…放一旁", example: "Set aside some money for emergencies." },
  { phrase: "set back", meaning: "推迟；使花费；阻碍", example: "The accident set us back three weeks." },
  { phrase: "set down", meaning: "记下；放下；制定", example: "Set down your thoughts on paper." },
  { phrase: "set fire to", meaning: "点燃", example: "He set fire to the barn." },
  { phrase: "set free", meaning: "释放", example: "The prisoners were set free." },
  { phrase: "set off", meaning: "出发；引爆；衬托", example: "We set off at dawn." },
  { phrase: "set out", meaning: "出发；开始；陈述", example: "They set out on a journey." },
  { phrase: "set up", meaning: "建立；创立；安排", example: "Set up your own business." },
  { phrase: "settle down", meaning: "定居；平静下来", example: "When are you going to settle down?" },
  { phrase: "shake off", meaning: "摆脱；抖落", example: "Shake off the dust." },
  { phrase: "shout at", meaning: "对…大声叫嚷", example: "Don't shout at me!" },
  { phrase: "show around", meaning: "带领…参观", example: "He showed us around the city." },
  { phrase: "show off", meaning: "炫耀", example: "Stop showing off!" },
  { phrase: "shut down", meaning: "关闭；停工", example: "The factory shut down last year." },
  { phrase: "shut off", meaning: "关掉；切断；隔绝", example: "Shut off the water." },
  { phrase: "shut up", meaning: "闭嘴；关闭", example: "Shut up!" },
  { phrase: "side by side", meaning: "肩并肩地；一起", example: "Walk side by side." },
  { phrase: "sign in", meaning: "签到；登记", example: "Please sign in at the front desk." },
  { phrase: "sign out", meaning: "签名离开", example: "He signed out of the hotel." },
  { phrase: "sign up", meaning: "签约雇用；报名参加", example: "Sign up for the course." },
  { phrase: "sit back", meaning: "休息；不采取行动", example: "Sit back and relax." },
  { phrase: "sit for", meaning: "参加（考试）；坐着供人画像", example: "She's sitting for her portrait." },
  { phrase: "sit in", meaning: "列席；旁听；静坐示威", example: "He sat in on the meeting." },
  { phrase: "sit up", meaning: "坐直；熬夜", example: "We sat up all night talking." },
  { phrase: "size up", meaning: "估计；判断", example: "He sized up the situation." },
  { phrase: "sleep in", meaning: "睡过头；睡懒觉", example: "I slept in and missed the bus." },
  { phrase: "slow down", meaning: "减速；放慢", example: "Slow down, please." },
  { phrase: "smell of", meaning: "有…的气味", example: "The room smells of smoke." },
  { phrase: "so as to", meaning: "以便；为了", example: "He spoke loudly so as to be heard." },
  { phrase: "so far", meaning: "到目前为止", example: "So far so good." },
  { phrase: "so long as", meaning: "只要", example: "You may go, so long as you come back early." },
  { phrase: "so that", meaning: "以便；所以", example: "Speak louder so that everyone can hear." },
  { phrase: "sooner or later", meaning: "迟早，早晚", example: "Sooner or later, you'll understand." },
  { phrase: "sort of", meaning: "有几分；稍微", example: "I'm sort of tired." },
  { phrase: "speak of", meaning: "谈到；值得一提", example: "Nothing to speak of." },
  { phrase: "speed up", meaning: "加速", example: "We need to speed up the process." },
  { phrase: "stand by", meaning: "支持；袖手旁观；准备行动", example: "Please stand by for further news." },
  { phrase: "stand for", meaning: "代表；主张；容忍", example: "What does UN stand for?" },
  { phrase: "stand out", meaning: "突出；引人注目", example: "Her red dress stood out in the crowd." },
  { phrase: "stand up for", meaning: "支持；维护", example: "Stand up for your rights." },
  { phrase: "stare at", meaning: "凝视", example: "Don't stare at people." },
  { phrase: "start off", meaning: "出发；开始", example: "Let's start off early." },
  { phrase: "start out", meaning: "开始；着手", example: "He started out as a clerk." },
  { phrase: "stay away", meaning: "离开；不打扰", example: "Stay away from that dog!" },
  { phrase: "stay behind", meaning: "留下来不走", example: "He stayed behind after class." },
  { phrase: "stay up", meaning: "熬夜", example: "I stayed up late watching TV." },
  { phrase: "step by step", meaning: "逐步地", example: "Learn to walk step by step." },
  { phrase: "step in", meaning: "介入；干预", example: "The police stepped in to stop the fight." },
  { phrase: "step up", meaning: "增加；加快；提升", example: "Step up production." },
  { phrase: "stick out", meaning: "伸出；显眼；坚持", example: "Stick out your tongue." },
  { phrase: "stick to", meaning: "坚持；粘在…上", example: "Stick to your principles." },
  { phrase: "stop by", meaning: "顺便停留", example: "I'll stop by your house later." },
  { phrase: "store up", meaning: "储藏；积聚", example: "Store up energy for the winter." },
  { phrase: "strike up", meaning: "开始（交谈）；建立（友谊）；演奏", example: "They struck up a conversation." },
  { phrase: "struggle against", meaning: "与…作斗争", example: "Struggle against injustice." },
  { phrase: "succeed in", meaning: "在…方面成功", example: "He succeeded in winning the race." },
  { phrase: "such being the case", meaning: "既然如此", example: "Such being the case, we can't go on." },
  { phrase: "suffer from", meaning: "遭受；患…病", example: "She suffers from headaches." },
  { phrase: "sum up", meaning: "总结", example: "To sum up, it was a success." },
  { phrase: "supply … with", meaning: "向…供应…", example: "They supplied us with food." },
  { phrase: "switch off", meaning: "关掉", example: "Switch off the light." },
  { phrase: "switch on", meaning: "打开", example: "Switch on the radio." },
  { phrase: "take a chance", meaning: "冒险；投机", example: "Take a chance and apply." },
  { phrase: "take a walk", meaning: "散步", example: "Let's take a walk." },
  { phrase: "take account of", meaning: "考虑到，顾及", example: "You must take account of the cost." },
  { phrase: "take advantage of", meaning: "利用；占…的便宜", example: "Take advantage of the opportunity." },
  { phrase: "take after", meaning: "长得像；性格像", example: "She takes after her mother." },
  { phrase: "take apart", meaning: "拆开；严厉批评", example: "Take the clock apart." },
  { phrase: "take away", meaning: "拿走；减去；使离开", example: "Take away the dirty dishes." },
  { phrase: "take back", meaning: "收回；退回", example: "I take back what I said." },
  { phrase: "take care", meaning: "小心；保重", example: "Take care of yourself." },
  { phrase: "take charge of", meaning: "掌管，负责", example: "Who will take charge of the department?" },
  { phrase: "take delight in", meaning: "以…为乐", example: "He takes delight in teasing his sister." },
  { phrase: "take down", meaning: "记下；拆卸", example: "Take down his phone number." },
  { phrase: "take effect", meaning: "生效；起作用", example: "The medicine took effect quickly." },
  { phrase: "take … for granted", meaning: "认为…理所当然", example: "Don't take your health for granted." },
  { phrase: "take hold of", meaning: "抓住；握住", example: "Take hold of the rope." },
  { phrase: "take in", meaning: "吸收；理解；欺骗", example: "I couldn't take in all the information." },
  { phrase: "take into account", meaning: "考虑", example: "We must take all factors into account." },
  { phrase: "take it easy", meaning: "放松；别紧张", example: "Take it easy, everything will be fine." },
  { phrase: "take note of", meaning: "注意；记下", example: "Take note of the instructions." },
  { phrase: "take notice of", meaning: "注意到", example: "Nobody took notice of him." },
  { phrase: "take off", meaning: "脱下；起飞；开始成功", example: "The plane took off on time." },
  { phrase: "take on", meaning: "承担；呈现；雇佣", example: "He took on too much work." },
  { phrase: "take one's time", meaning: "不着急，慢慢来", example: "Take your time, there's no rush." },
  { phrase: "take over", meaning: "接管；接替", example: "He took over the family business." },
  { phrase: "take pains", meaning: "尽力，煞费苦心", example: "She took great pains with her work." },
  { phrase: "take part in", meaning: "参加", example: "We took part in the race." },
  { phrase: "take place", meaning: "发生；举行", example: "The wedding took place in a church." },
  { phrase: "take root", meaning: "生根；扎根", example: "The plants took root quickly." },
  { phrase: "take shape", meaning: "成形；具体化", example: "Our plans are taking shape." },
  { phrase: "take sides", meaning: "偏袒；站在…一边", example: "Don't take sides in their argument." },
  { phrase: "take to", meaning: "喜欢上；开始从事；逃到", example: "He took to the new job immediately." },
  { phrase: "take turns", meaning: "轮流", example: "We took turns driving." },
  { phrase: "take up", meaning: "开始从事；占据；接受", example: "She took up painting." },
  { phrase: "talk back", meaning: "顶嘴", example: "Don't talk back to your parents." },
  { phrase: "talk into", meaning: "说服…做…", example: "He talked me into buying the car." },
  { phrase: "talk out of", meaning: "说服…不做…", example: "She talked him out of leaving." },
  { phrase: "talk over", meaning: "讨论；商量", example: "Let's talk it over." },
  { phrase: "tear down", meaning: "拆毁；扯下", example: "They tore down the old school." },
  { phrase: "tear up", meaning: "撕毁", example: "He tore up the letter." },
  { phrase: "tell … apart", meaning: "区分…", example: "Can you tell the twins apart?" },
  { phrase: "tell … from", meaning: "把…与…区分开", example: "Tell right from wrong." },
  { phrase: "tend to", meaning: "倾向于；照料", example: "He tends to be late." },
  { phrase: "thanks to", meaning: "由于；多亏", example: "Thanks to his help, we finished early." },
  { phrase: "that is to say", meaning: "也就是说", example: "He's very busy, that is to say, he has no time." },
  { phrase: "the moment (that)", meaning: "一…就…", example: "The moment I saw her, I knew." },
  { phrase: "think about", meaning: "考虑；回想", example: "I'll think about it." },
  { phrase: "think of", meaning: "想起；认为；考虑", example: "What do you think of this?" },
  { phrase: "think out", meaning: "仔细考虑；想通", example: "Think out your plan carefully." },
  { phrase: "think over", meaning: "仔细考虑", example: "Think it over before you decide." },
  { phrase: "throw away", meaning: "扔掉；浪费", example: "Don't throw away your chance." },
  { phrase: "throw light on", meaning: "阐明", example: "The research threw light on the issue." },
  { phrase: "throw off", meaning: "摆脱；匆匆脱掉", example: "Throw off your coat." },
  { phrase: "throw up", meaning: "呕吐；匆匆建造；辞去", example: "The smell made me throw up." },
  { phrase: "tire of", meaning: "对…厌倦", example: "I never tire of this view." },
  { phrase: "to a degree", meaning: "非常；在一定程度上", example: "He is stubborn to a degree." },
  { phrase: "to a certain extent", meaning: "在一定程度上", example: "To a certain extent, I agree." },
  { phrase: "to date", meaning: "到目前为止", example: "To date, we've received 100 replies." },
  { phrase: "to excess", meaning: "过度，过分", example: "Don't drink to excess." },
  { phrase: "to no avail", meaning: "完全无用", example: "We tried, but to no avail." },
  { phrase: "to one's astonishment", meaning: "令人吃惊的是", example: "To my astonishment, he didn't come." },
  { phrase: "to one's delight", meaning: "令人高兴的是", example: "To my delight, I passed the exam." },
  { phrase: "to one's feet", meaning: "站起来", example: "The audience rose to their feet." },
  { phrase: "to one's heart's content", meaning: "尽情地", example: "You can eat to your heart's content." },
  { phrase: "to one's knowledge", meaning: "据某人所知", example: "To my knowledge, he is honest." },
  { phrase: "to one's surprise", meaning: "令人惊讶的是", example: "To my surprise, he agreed." },
  { phrase: "to one's taste", meaning: "合某人的口味", example: "This music is not to my taste." },
  { phrase: "to the contrary", meaning: "相反地", example: "There is no evidence to the contrary." },
  { phrase: "to the full", meaning: "充分地", example: "Enjoy life to the full." },
  { phrase: "to the point", meaning: "切题；中肯", example: "Keep your remarks to the point." },
  { phrase: "together with", meaning: "与…一起；连同", example: "He, together with his friends, came to the party." },
  { phrase: "too … to", meaning: "太…而不能…", example: "It's too cold to swim." },
  { phrase: "touch on", meaning: "涉及；谈及", example: "He touched on the main issues." },
  { phrase: "track down", meaning: "追踪到；追查", example: "The police tracked down the criminal." },
  { phrase: "trade in", meaning: "经营；以旧换新", example: "He trades in used cars." },
  { phrase: "try on", meaning: "试穿；试戴", example: "Can I try on this dress?" },
  { phrase: "try out", meaning: "试用；试验", example: "Try out the new software." },
  { phrase: "tune in", meaning: "收听；收看", example: "Tune in to our next programme." },
  { phrase: "turn around", meaning: "转身；好转", example: "Turn around and let me look at you." },
  { phrase: "turn away", meaning: "把…打发走；拒绝", example: "He was turned away at the door." },
  { phrase: "turn back", meaning: "折回；翻回", example: "It's too late to turn back." },
  { phrase: "turn down", meaning: "关小；拒绝", example: "Turn down the volume." },
  { phrase: "turn in", meaning: "上交；睡觉", example: "Turn in your homework." },
  { phrase: "turn off", meaning: "关掉", example: "Turn off the TV." },
  { phrase: "turn on", meaning: "打开", example: "Turn on the light." },
  { phrase: "turn out", meaning: "结果是；生产；出动", example: "It turned out to be true." },
  { phrase: "turn over", meaning: "翻过来；移交；营业额达到", example: "Turn over the page." },
  { phrase: "turn to", meaning: "转向；求助于；翻到", example: "He turned to his friend for help." },
  { phrase: "turn up", meaning: "出现；调大；翻起", example: "He turned up late." },
  { phrase: "under construction", meaning: "在建造中", example: "The bridge is under construction." },
  { phrase: "under control", meaning: "被控制住", example: "The fire is under control." },
  { phrase: "under discussion", meaning: "在讨论中", example: "The plan is under discussion." },
  { phrase: "under investigation", meaning: "在调查中", example: "The matter is under investigation." },
  { phrase: "under repair", meaning: "在修理中", example: "The road is under repair." },
  { phrase: "under way", meaning: "在进行中", example: "Preparations are under way." },
  { phrase: "up to", meaning: "直到；多达；胜任；取决于", example: "It's up to you." },
  { phrase: "up to date", meaning: "现代的；最新的", example: "Keep your knowledge up to date." },
  { phrase: "use up", meaning: "用完", example: "We used up all the paper." },
  { phrase: "used to", meaning: "过去经常", example: "I used to live here." },
  { phrase: "vary from … to", meaning: "从…到…不等", example: "Prices vary from $10 to $50." },
  { phrase: "vote for", meaning: "投票赞成", example: "Who did you vote for?" },
  { phrase: "wait on", meaning: "服侍；招待", example: "She waited on the customers." },
  { phrase: "wake up", meaning: "醒来；叫醒", example: "Wake me up at seven." },
  { phrase: "warm up", meaning: "热身；变暖", example: "Let's warm up before the game." },
  { phrase: "wash up", meaning: "洗餐具；洗手洗脸", example: "I'll wash up after dinner." },
  { phrase: "watch out", meaning: "当心", example: "Watch out for the ice!" },
  { phrase: "wear away", meaning: "磨损；消逝", example: "The inscription has worn away." },
  { phrase: "wear off", meaning: "逐渐消失；磨损", example: "The novelty wore off quickly." },
  { phrase: "wear out", meaning: "穿破；使疲乏", example: "I'm worn out." },
  { phrase: "wind up", meaning: "结束；上发条；卷起", example: "Let's wind up the meeting." },
  { phrase: "wipe out", meaning: "彻底消灭；擦掉", example: "The disease was wiped out." },
  { phrase: "with reference to", meaning: "关于", example: "With reference to your letter, we are pleased to reply." },
  { phrase: "with regard to", meaning: "关于", example: "With regard to your question, here is the answer." },
  { phrase: "with the exception of", meaning: "除…之外", example: "All was quiet, with the exception of the ticking clock." },
  { phrase: "without exception", meaning: "毫无例外", example: "All students, without exception, must attend." },
  { phrase: "word for word", meaning: "逐字地", example: "Repeat what he said word for word." },
  { phrase: "work at", meaning: "从事于；致力于", example: "He's working at his novel." },
  { phrase: "work off", meaning: "消除；发泄", example: "Work off your anger by running." },
  { phrase: "work on", meaning: "继续工作；影响；努力说服", example: "We're working on a solution." },
  { phrase: "work out", meaning: "解决；计算出；锻炼；结果", example: "Work out the answer." },
  { phrase: "worry about", meaning: "担心", example: "Don't worry about me." },
  { phrase: "would rather … than", meaning: "宁愿…也不…", example: "I'd rather walk than take a bus." },
  { phrase: "write back", meaning: "回信", example: "Write back soon!" },
  { phrase: "write off", meaning: "注销；取消；一口气写成", example: "The debt was written off." },
  { phrase: "yield to", meaning: "屈服于；让步", example: "Don't yield to temptation." },
  { phrase: "zeal for", meaning: "对…的热情", example: "She showed great zeal for her work." },
  { phrase: "zoom in", meaning: "放大；拉近镜头", example: "Zoom in on the map." },
  { phrase: "zoom out", meaning: "缩小；拉远镜头", example: "Zoom out to see the whole picture." }
];
