window.CET6_WORDS = [
  { word: "abnormal", phonetic: "/æbˈnɔːrml/", meaning: "反常的，异常的", pos: "a.", headword: true, example: "The weather is abnormal for July." },
  { word: "abolish", phonetic: "/əˈbɒlɪʃ/", meaning: "废除(法律,习惯等)，取消", pos: "vt.", headword: true, example: "Slavery was abolished in 1865." },
  { word: "abrupt", phonetic: "/əˈbrʌpt/", meaning: "突然的，意外的", pos: "a.", headword: true, example: "An abrupt stop." },
  { word: "absurd", phonetic: "/əbˈsɜːrd/", meaning: "荒谬的，荒唐的", pos: "a.", headword: true, example: "An absurd idea." },
  { word: "abundance", phonetic: "/əˈbʌndəns/", meaning: "丰富，充裕", pos: "n.", headword: true, example: "An abundance of food." },
  { word: "accessory", phonetic: "/əkˈsesəri/", meaning: "附件，配件；同谋", pos: "n.", headword: true, example: "Car accessories." },
  { word: "accommodate", phonetic: "/əˈkɒmədeɪt/", meaning: "容纳；供给食宿；使适应", pos: "vt.", headword: true, example: "The hotel can accommodate 200 guests." },
  { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", meaning: "承认；告知收到；致谢", pos: "vt.", headword: true, example: "He acknowledged his mistake." },
  { word: "acquaint", phonetic: "/əˈkweɪnt/", meaning: "使认识，使了解", pos: "vt.", headword: true, example: "You should acquaint yourself with the rules." },
  { word: "acquisition", phonetic: "/ˌækwɪˈzɪʃn/", meaning: "获得；获得物", pos: "n.", headword: true, example: "The museum's latest acquisition is a Picasso." },
  { word: "activate", phonetic: "/ˈæktɪveɪt/", meaning: "激活；使活动", pos: "vt.", headword: true, example: "Activate the system." },
  { word: "acute", phonetic: "/əˈkjuːt/", meaning: "严重的；急性的；敏锐的", pos: "a.", headword: true, example: "An acute shortage of water." },
  { word: "adhere", phonetic: "/ədˈhɪr/", meaning: "黏附；坚持，遵守", pos: "vi.", headword: true, example: "We must adhere to the plan." },
  { word: "adjacent", phonetic: "/əˈdʒeɪsnt/", meaning: "邻近的，毗连的", pos: "a.", headword: true, example: "The hotel is adjacent to the park." },
  { word: "administer", phonetic: "/ədˈmɪnɪstər/", meaning: "管理；执行；给予", pos: "vt.", headword: true, example: "He administers a large company." },
  { word: "adolescent", phonetic: "/ˌædəˈlesnt/", meaning: "青少年；青春期的", pos: "n. & a.", headword: true, example: "Adolescent problems." },
  { word: "advent", phonetic: "/ˈædvent/", meaning: "出现，到来", pos: "n.", headword: true, example: "The advent of the internet." },
  { word: "adverse", phonetic: "/ˈædvɜːrs/", meaning: "不利的，有害的", pos: "a.", headword: true, example: "Adverse weather conditions." },
  { word: "advocate", phonetic: "/ˈædvəkeɪt/", meaning: "提倡者；辩护者；提倡", pos: "n. & vt.", headword: true, example: "He is an advocate of free speech." },
  { word: "aerial", phonetic: "/ˈeəriəl/", meaning: "航空的；空气的；天线", pos: "a. & n.", headword: true, example: "An aerial photograph." },
  { word: "aesthetic", phonetic: "/iːsˈθetɪk/", meaning: "美学的；审美的；美观的", pos: "a.", headword: true, example: "Aesthetic value." },
  { word: "affection", phonetic: "/əˈfekʃn/", meaning: "喜爱，感情，爱慕之情", pos: "n.", headword: true, example: "She has a deep affection for her grandfather." },
  { word: "affiliate", phonetic: "/əˈfɪlieɪt/", meaning: "使隶属；附属机构", pos: "vt. & n.", headword: true, example: "The hospital is affiliated with the university." },
  { word: "affirm", phonetic: "/əˈfɜːrm/", meaning: "断言，坚持声称；证实", pos: "vt.", headword: true, example: "He affirmed his innocence." },
  { word: "afflict", phonetic: "/əˈflɪkt/", meaning: "使痛苦，折磨", pos: "vt.", headword: true, example: "He was afflicted with a disease." },
  { word: "agenda", phonetic: "/əˈdʒendə/", meaning: "议事日程", pos: "n.", headword: true, example: "What's on the agenda today?" },
  { word: "aggravate", phonetic: "/ˈæɡrəveɪt/", meaning: "加重，恶化；激怒", pos: "vt.", headword: true, example: "Smoking aggravates the condition." },
  { word: "aggregate", phonetic: "/ˈæɡrɪɡət/", meaning: "总计的；集合；总计", pos: "a. & n. & vt.", headword: true, example: "The aggregate amount of money." },
  { word: "agony", phonetic: "/ˈæɡəni/", meaning: "极度痛苦，苦恼", pos: "n.", headword: true, example: "He was in agony." },
  { word: "agreeable", phonetic: "/əˈɡriːəbl/", meaning: "令人愉快的；同意的", pos: "a.", headword: true, example: "The weather is agreeable." },
  { word: "alien", phonetic: "/ˈeɪliən/", meaning: "外国的；陌生的；外星人", pos: "a. & n.", headword: true, example: "An alien culture." },
  { word: "allege", phonetic: "/əˈledʒ/", meaning: "宣称，断言(未证实)", pos: "vt.", headword: true, example: "He alleged that he was at home." },
  { word: "alleviate", phonetic: "/əˈliːvieɪt/", meaning: "减轻，缓解", pos: "vt.", headword: true, example: "Take medicine to alleviate the pain." },
  { word: "allocate", phonetic: "/ˈæləkeɪt/", meaning: "分配，分派", pos: "vt.", headword: true, example: "Allocate funds for the project." },
  { word: "allowance", phonetic: "/əˈlaʊəns/", meaning: "津贴，补贴；零用钱", pos: "n.", headword: true, example: "He receives a weekly allowance." },
  { word: "alloy", phonetic: "/ˈælɔɪ/", meaning: "合金；将…铸成合金", pos: "n. & vt.", headword: true, example: "An alloy of copper and zinc." },
  { word: "ally", phonetic: "/ˈælaɪ/", meaning: "同盟国；盟友；使结盟", pos: "n. & vt.", headword: true, example: "A loyal ally." },
  { word: "alongside", phonetic: "/əˌlɒŋˈsaɪd/", meaning: "在…旁边；与…并肩", pos: "prep. & ad.", headword: true, example: "Walk alongside me." },
  { word: "alternate", phonetic: "/ˈɔːltərnət/", meaning: "交替的；轮流的；使交替", pos: "a. & vi. & vt.", headword: true, example: "Alternate hot and cold." },
  { word: "amateur", phonetic: "/ˈæmətər/", meaning: "业余爱好者；业余的", pos: "n. & a.", headword: true, example: "He is an amateur photographer." },
  { word: "ambassador", phonetic: "/æmˈbæsədər/", meaning: "大使，使节", pos: "n.", headword: true, example: "The Chinese ambassador." },
  { word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/", meaning: "含糊的，不明确的", pos: "a.", headword: true, example: "An ambiguous answer." },
  { word: "ambitious", phonetic: "/æmˈbɪʃəs/", meaning: "有雄心的，野心勃勃的", pos: "a.", headword: true, example: "He is an ambitious young man." },
  { word: "amend", phonetic: "/əˈmend/", meaning: "修改，修订；改良", pos: "vt.", headword: true, example: "Amend the constitution." },
  { word: "amends", phonetic: "/əˈmendz/", meaning: "赔偿，赔罪", pos: "n.", headword: true, example: "Make amends for the mistake." },
  { word: "ample", phonetic: "/ˈæmpl/", meaning: "足够的；宽敞的", pos: "a.", headword: true, example: "Ample evidence." },
  { word: "amplify", phonetic: "/ˈæmplɪfaɪ/", meaning: "放大，增强；详述", pos: "vt.", headword: true, example: "Amplify the sound." },
  { word: "analogy", phonetic: "/əˈnælədʒi/", meaning: "类似，相似；类比", pos: "n.", headword: true, example: "Draw an analogy." },
  { word: "analytic", phonetic: "/ˌænəˈlɪtɪk/", meaning: "分析的；分析法的", pos: "a.", headword: true, example: "An analytic approach." },
  { word: "angel", phonetic: "/ˈeɪndʒl/", meaning: "天使；可爱的人", pos: "n.", headword: true, example: "An angel of mercy." },
  { word: "anniversary", phonetic: "/ˌænɪˈvɜːrsəri/", meaning: "周年纪念日", pos: "n.", headword: true, example: "Wedding anniversary." },
  { word: "anonymous", phonetic: "/əˈnɒnɪməs/", meaning: "匿名的；无名的", pos: "a.", headword: true, example: "An anonymous letter." },
  { word: "antarctic", phonetic: "/ænˈtɑːrktɪk/", meaning: "南极的；南极地区", pos: "a. & n.", headword: true, example: "Antarctic ice." },
  { word: "antique", phonetic: "/ænˈtiːk/", meaning: "古董；古老的", pos: "n. & a.", headword: true, example: "An antique shop." },
  { word: "apparatus", phonetic: "/ˌæpəˈrætəs/", meaning: "器械，仪器；机构", pos: "n.", headword: true, example: "Laboratory apparatus." },
  { word: "appease", phonetic: "/əˈpiːz/", meaning: "平息，安抚；绥靖", pos: "vt.", headword: true, example: "Appease a crying child." },
  { word: "appendix", phonetic: "/əˈpendɪks/", meaning: "附录；阑尾", pos: "n.", headword: true, example: "See the appendix." },
  { word: "applaud", phonetic: "/əˈplɔːd/", meaning: "鼓掌，喝彩", pos: "vi. & vt.", headword: true, example: "The audience applauded loudly." },
  { word: "appraisal", phonetic: "/əˈpreɪzl/", meaning: "评价，评估", pos: "n.", headword: true, example: "Performance appraisal." },
  { word: "appreciable", phonetic: "/əˈpriːʃəbl/", meaning: "可估计的；明显的", pos: "a.", headword: true, example: "An appreciable improvement." },
  { word: "apprehension", phonetic: "/ˌæprɪˈhenʃn/", meaning: "忧虑；理解；逮捕", pos: "n.", headword: true, example: "Feel apprehension about the future." },
  { word: "apt", phonetic: "/æpt/", meaning: "恰当的；有…倾向的", pos: "a.", headword: true, example: "An apt description." },
  { word: "arc", phonetic: "/ɑːrk/", meaning: "弧，弧形；电弧", pos: "n.", headword: true, example: "Draw an arc." },
  { word: "arch", phonetic: "/ɑːrtʃ/", meaning: "拱门；拱形；使成弓形", pos: "n. & vt. & vi.", headword: true, example: "The arch of the bridge." },
  { word: "arena", phonetic: "/əˈriːnə/", meaning: "竞技场；活动领域", pos: "n.", headword: true, example: "A sports arena." },
  { word: "armo(u)r", phonetic: "/ˈɑːrmər/", meaning: "盔甲；装甲；提供保护", pos: "n. & vt.", headword: true, example: "A suit of armour." },
  { word: "array", phonetic: "/əˈreɪ/", meaning: "一系列；排列；列阵", pos: "n. & vt.", headword: true, example: "An array of data." },
  { word: "arrogant", phonetic: "/ˈærəɡənt/", meaning: "傲慢的，自大的", pos: "a.", headword: true, example: "An arrogant attitude." },
  { word: "artery", phonetic: "/ˈɑːrtəri/", meaning: "动脉；干线", pos: "n.", headword: true, example: "Main artery." },
  { word: "articulate", phonetic: "/ɑːrˈtɪkjuleɪt/", meaning: "发音清晰的；清楚表达", pos: "a. & vt.", headword: true, example: "Articulate your thoughts." },
  { word: "ascend", phonetic: "/əˈsend/", meaning: "上升，攀登；升高", pos: "vi. & vt.", headword: true, example: "Ascend the mountain." },
  { word: "ascertain", phonetic: "/ˌæsərˈteɪn/", meaning: "查明，确定", pos: "vt.", headword: true, example: "Ascertain the facts." },
  { word: "ascribe", phonetic: "/əˈskraɪb/", meaning: "把…归因于；把…归属于", pos: "vt.", headword: true, example: "He ascribes his success to luck." },
  { word: "aspiration", phonetic: "/ˌæspəˈreɪʃn/", meaning: "渴望，抱负，志向", pos: "n.", headword: true, example: "Young people's aspirations." },
  { word: "assassination", phonetic: "/əˌsæsɪˈneɪʃn/", meaning: "暗杀，行刺", pos: "n.", headword: true, example: "The assassination of a president." },
  { word: "assault", phonetic: "/əˈsɔːlt/", meaning: "攻击，袭击；抨击", pos: "n. & vt.", headword: true, example: "An assault on the fort." },
  { word: "assert", phonetic: "/əˈsɜːrt/", meaning: "断言，宣称；维护", pos: "vt.", headword: true, example: "He asserted his innocence." },
  { word: "asset", phonetic: "/ˈæset/", meaning: "资产；有价值的人(或物)", pos: "n.", headword: true, example: "Knowledge is an asset." },
  { word: "assimilate", phonetic: "/əˈsɪməleɪt/", meaning: "同化；吸收，消化", pos: "vt. & vi.", headword: true, example: "Assimilate knowledge." },
  { word: "assumption", phonetic: "/əˈsʌmpʃn/", meaning: "假定，设想", pos: "n.", headword: true, example: "That is a risky assumption." },
  { word: "assurance", phonetic: "/əˈʃʊrəns/", meaning: "保证；保险；信心", pos: "n.", headword: true, example: "Give me your assurance." },
  { word: "astronomy", phonetic: "/əˈstrɒnəmi/", meaning: "天文学", pos: "n.", headword: true, example: "Study astronomy." },
  { word: "athlete", phonetic: "/ˈæθliːt/", meaning: "运动员", pos: "n.", headword: true, example: "Professional athlete." },
  { word: "atlas", phonetic: "/ˈætləs/", meaning: "地图集", pos: "n.", headword: true, example: "A world atlas." },
  { word: "attendance", phonetic: "/əˈtendəns/", meaning: "出席；参加；出席人数", pos: "n.", headword: true, example: "Attendance is mandatory." },
  { word: "attendant", phonetic: "/əˈtendənt/", meaning: "服务员；随从；伴随的", pos: "n. & a.", headword: true, example: "A parking attendant." },
  { word: "attorney", phonetic: "/əˈtɜːrni/", meaning: "律师；代理人", pos: "n.", headword: true, example: "Defense attorney." },
  { word: "attribute", phonetic: "/əˈtrɪbjuːt/", meaning: "把…归因于；属性", pos: "vt. & n.", headword: true, example: "Attribute success to hard work." },
  { word: "auction", phonetic: "/ˈɔːkʃn/", meaning: "拍卖；竞卖", pos: "n. & vt.", headword: true, example: "Sell at auction." },
  { word: "authentic", phonetic: "/ɔːˈθentɪk/", meaning: "真正的；真实的；可信的", pos: "a.", headword: true, example: "An authentic signature." },
  { word: "authorise/authorize", phonetic: "/ˈɔːθəraɪz/", meaning: "授权；批准", pos: "vt.", headword: true, example: "He was authorized to act." },
  { word: "automation", phonetic: "/ˌɔːtəˈmeɪʃn/", meaning: "自动化；自动操作", pos: "n.", headword: true, example: "Office automation." },
  { word: "autonomy", phonetic: "/ɔːˈtɒnəmi/", meaning: "自治；自治权；自主", pos: "n.", headword: true, example: "Regional autonomy." },
  { word: "avail", phonetic: "/əˈveɪl/", meaning: "有用；帮助；效用", pos: "vt. & vi. & n.", headword: true, example: "All his efforts availed him nothing." },
  { word: "avert", phonetic: "/əˈvɜːrt/", meaning: "避免，防止；转移(目光等)", pos: "vt.", headword: true, example: "Avert a crisis." },
  { word: "aviation", phonetic: "/ˌeɪviˈeɪʃn/", meaning: "航空；航空学", pos: "n.", headword: true, example: "Civil aviation." },
  { word: "axis", phonetic: "/ˈæksɪs/", meaning: "轴；轴线；坐标轴", pos: "n.", headword: true, example: "The earth rotates on its axis." }
];
