window.CET4_PHRASES = [
  { phrase: "a bit", meaning: "一点；有点儿", example: "I'm a bit tired." },
  { phrase: "a couple of", meaning: "两个；几个", example: "I need a couple of days." },
  { phrase: "a few", meaning: "几个；少数", example: "A few students came." },
  { phrase: "a great deal of", meaning: "大量（修饰不可数名词）", example: "She has a great deal of experience." },
  { phrase: "a little", meaning: "一点；少许", example: "I speak a little English." },
  { phrase: "a lot of", meaning: "许多", example: "There are a lot of people." },
  { phrase: "a number of", meaning: "许多；若干", example: "A number of factors led to the decision." },
  { phrase: "a series of", meaning: "一系列；一连串", example: "A series of accidents happened." },
  { phrase: "above all", meaning: "最重要的是；尤其是", example: "Above all, be honest." },
  { phrase: "according to", meaning: "根据；按照", example: "According to the report, the economy is improving." },
  { phrase: "add up to", meaning: "总计达；意味着", example: "The total adds up to 500." },
  { phrase: "after all", meaning: "毕竟；终究", example: "After all, he is just a child." },
  { phrase: "again and again", meaning: "再三地，反复地", example: "He asked the same question again and again." },
  { phrase: "ahead of", meaning: "在…前面；早于", example: "She arrived ahead of time." },
  { phrase: "all at once", meaning: "突然；同时", example: "All at once, the lights went out." },
  { phrase: "all in all", meaning: "总的来说；大体而言", example: "All in all, it was a good trip." },
  { phrase: "all over", meaning: "到处；遍及；结束", example: "I looked all over for my keys." },
  { phrase: "all right", meaning: "好的；没问题；良好的", example: "Are you feeling all right?" },
  { phrase: "all the same", meaning: "仍然；还是", example: "He's not perfect, but I love him all the same." },
  { phrase: "allow for", meaning: "考虑到；顾及；允许有", example: "We must allow for delays." },
  { phrase: "and so on", meaning: "等等", example: "We bought apples, oranges, bananas, and so on." },
  { phrase: "answer for", meaning: "对…负责；为…担保", example: "You will have to answer for your actions." },
  { phrase: "apply for", meaning: "申请", example: "I applied for a new job." },
  { phrase: "as a matter of fact", meaning: "事实上；其实", example: "As a matter of fact, I agree with you." },
  { phrase: "as a result", meaning: "结果；因此", example: "He worked hard; as a result, he succeeded." },
  { phrase: "as a rule", meaning: "通常；一般说来", example: "As a rule, I get up at six." },
  { phrase: "as far as", meaning: "就…而言；至于", example: "As far as I know, he is reliable." },
  { phrase: "as follows", meaning: "如下", example: "The results are as follows." },
  { phrase: "as if", meaning: "好像；仿佛", example: "He acts as if he owns the place." },
  { phrase: "as long as", meaning: "只要；既然", example: "You can stay as long as you like." },
  { phrase: "as soon as", meaning: "一…就…", example: "Come as soon as possible." },
  { phrase: "as though", meaning: "好像；仿佛", example: "It looks as though it might rain." },
  { phrase: "as to", meaning: "关于；至于", example: "He asked as to my plans." },
  { phrase: "as usual", meaning: "像往常一样；照例", example: "She is late, as usual." },
  { phrase: "as well", meaning: "也；同样地", example: "I can do it as well." },
  { phrase: "as well as", meaning: "以及；和…一样", example: "He speaks English as well as French." },
  { phrase: "at a loss", meaning: "困惑；不知所措", example: "I'm at a loss for words." },
  { phrase: "at all", meaning: "根本；丝毫", example: "I don't like it at all." },
  { phrase: "at any rate", meaning: "无论如何；至少", example: "At any rate, we must finish today." },
  { phrase: "at first", meaning: "最初；起先", example: "At first, I found it difficult." },
  { phrase: "at hand", meaning: "在手边；即将到来", example: "Help is at hand." },
  { phrase: "at home", meaning: "在家；在国内；舒适自在", example: "Make yourself at home." },
  { phrase: "at last", meaning: "终于", example: "At last, the bus arrived." },
  { phrase: "at least", meaning: "至少；起码", example: "You will need at least 3 hours." },
  { phrase: "at once", meaning: "立刻；马上", example: "Do it at once!" },
  { phrase: "at present", meaning: "目前；现在", example: "At present, he is abroad." },
  { phrase: "at the cost of", meaning: "以…为代价", example: "He succeeded at the cost of his health." },
  { phrase: "at the moment", meaning: "此刻；目前", example: "I'm busy at the moment." },
  { phrase: "at the same time", meaning: "同时；然而", example: "I like it, but at the same time I'm worried." },
  { phrase: "back and forth", meaning: "来回地；反复地", example: "He paced back and forth." },
  { phrase: "be about to", meaning: "即将；正要", example: "The show is about to start." },
  { phrase: "be accustomed to", meaning: "习惯于", example: "I'm accustomed to early rising." },
  { phrase: "be aware of", meaning: "知道；意识到", example: "Are you aware of the problem?" },
  { phrase: "be based on", meaning: "基于；以…为基础", example: "The film is based on a true story." },
  { phrase: "be concerned about", meaning: "关心；担忧", example: "She is concerned about her health." },
  { phrase: "be fond of", meaning: "喜欢；喜爱", example: "He is fond of music." },
  { phrase: "be interested in", meaning: "对…感兴趣", example: "I'm interested in learning Chinese." },
  { phrase: "be known for", meaning: "因…而出名", example: "The city is known for its history." },
  { phrase: "be made up of", meaning: "由…组成", example: "The team is made up of experts." },
  { phrase: "be proud of", meaning: "为…感到自豪", example: "I'm proud of you." },
  { phrase: "be used to", meaning: "习惯于", example: "He is used to hard work." },
  { phrase: "bear in mind", meaning: "记住；牢记", example: "Bear in mind that it may rain." },
  { phrase: "because of", meaning: "因为；由于", example: "The game was cancelled because of rain." },
  { phrase: "before long", meaning: "不久以后", example: "Before long, she will return." },
  { phrase: "belong to", meaning: "属于", example: "This book belongs to me." },
  { phrase: "beyond expectation", meaning: "出乎意料", example: "The result was beyond expectation." },
  { phrase: "bit by bit", meaning: "一点一点地；逐渐地", example: "Bit by bit, he improved." },
  { phrase: "break down", meaning: "出故障；分解；打破；感情崩溃", example: "My car broke down." },
  { phrase: "break out", meaning: "爆发；突然发生", example: "A fire broke out last night." },
  { phrase: "break up", meaning: "打碎；分手；散会", example: "They decided to break up." },
  { phrase: "bring about", meaning: "导致；引起", example: "The reforms brought about great change." },
  { phrase: "bring up", meaning: "抚养；提出；呕吐", example: "She brought up three children." },
  { phrase: "by accident", meaning: "偶然；意外地", example: "I met her by accident." },
  { phrase: "by all means", meaning: "当然可以；尽一切办法", example: "By all means, take a look." },
  { phrase: "by chance", meaning: "偶然；碰巧", example: "I found it by chance." },
  { phrase: "by means of", meaning: "用；凭借", example: "He succeeded by means of hard work." },
  { phrase: "by mistake", meaning: "错误地", example: "I took your bag by mistake." },
  { phrase: "by no means", meaning: "绝不；并没有", example: "This is by no means easy." },
  { phrase: "by the way", meaning: "顺便说；附带说说", example: "By the way, have you seen John?" },
  { phrase: "call for", meaning: "需要；要求；去接(某人)", example: "This recipe calls for three eggs." },
  { phrase: "call off", meaning: "取消", example: "They called off the meeting." },
  { phrase: "call on", meaning: "拜访；号召", example: "I'll call on you tomorrow." },
  { phrase: "care about", meaning: "关心；在意", example: "Do you care about the environment?" },
  { phrase: "care for", meaning: "照顾；喜欢", example: "Who will care for the children?" },
  { phrase: "carry on", meaning: "继续；进行", example: "Let's carry on with the work." },
  { phrase: "carry out", meaning: "执行；实施；完成", example: "They carried out the plan." },
  { phrase: "catch up with", meaning: "赶上；追上", example: "I need to catch up with my work." },
  { phrase: "check in", meaning: "登记入住；办理登机手续", example: "We checked in at the hotel." },
  { phrase: "check out", meaning: "结账离开；检验", example: "They checked out at noon." },
  { phrase: "come across", meaning: "偶然遇见；偶然发现", example: "I came across an old friend." },
  { phrase: "come up with", meaning: "想出；提出", example: "She came up with a great idea." },
  { phrase: "compare to", meaning: "把…比作；与…相比", example: "He compared her to a rose." },
  { phrase: "compare with", meaning: "与…相比较", example: "Compared with last year, sales are up." },
  { phrase: "contribute to", meaning: "有助于；捐献；为…做贡献", example: "Exercise contributes to good health." },
  { phrase: "count on", meaning: "依靠；指望", example: "You can count on me." },
  { phrase: "cut down", meaning: "削减；砍倒", example: "We need to cut down expenses." },
  { phrase: "cut off", meaning: "切断；中断；隔离", example: "The power was cut off." },
  { phrase: "deal with", meaning: "处理；应对；与…打交道", example: "How do you deal with stress?" },
  { phrase: "depend on", meaning: "依赖；取决于", example: "Whether we go depends on the weather." },
  { phrase: "die down", meaning: "逐渐减弱；平息", example: "The wind died down." },
  { phrase: "do away with", meaning: "废除；去掉", example: "We should do away with outdated rules." },
  { phrase: "draw up", meaning: "起草；拟订", example: "They drew up a new contract." },
  { phrase: "drop in", meaning: "顺便走访", example: "Please drop in when you're free." },
  { phrase: "drop out", meaning: "退出；辍学", example: "He dropped out of college." },
  { phrase: "due to", meaning: "由于；因为", example: "The delay was due to bad weather." },
  { phrase: "each other", meaning: "互相", example: "They love each other." },
  { phrase: "even if", meaning: "即使；虽然", example: "Even if it rains, I'll go." },
  { phrase: "even though", meaning: "尽管；虽然", example: "Even though he tried, he failed." },
  { phrase: "ever since", meaning: "自从；从那时起", example: "Ever since we met, I've been happy." },
  { phrase: "every now and then", meaning: "时而；偶尔", example: "He calls me every now and then." },
  { phrase: "except for", meaning: "除了…以外；除去", example: "The room is empty except for a table." },
  { phrase: "face to face", meaning: "面对面", example: "We need to talk face to face." },
  { phrase: "fall behind", meaning: "落后；跟不上", example: "Don't fall behind in your studies." },
  { phrase: "far from", meaning: "远离；完全不", example: "The result is far from perfect." },
  { phrase: "figure out", meaning: "理解；弄清楚；计算出", example: "I can't figure out this problem." },
  { phrase: "fill in", meaning: "填写；临时替代", example: "Please fill in this form." },
  { phrase: "find out", meaning: "查明；发现", example: "We need to find out the truth." },
  { phrase: "first of all", meaning: "首先", example: "First of all, let me introduce myself." },
  { phrase: "for ever", meaning: "永远；总是", example: "I'll remember this for ever." },
  { phrase: "for example", meaning: "例如", example: "Many fruits, for example, oranges and apples, are healthy." },
  { phrase: "for good", meaning: "永久地；一劳永逸地", example: "He left the town for good." },
  { phrase: "for instance", meaning: "例如；比如", example: "Take, for instance, the case of Tom." },
  { phrase: "for the sake of", meaning: "为了…起见；看在…的份上", example: "For the sake of peace, let's agree." },
  { phrase: "for the time being", meaning: "暂时；眼下", example: "That's enough for the time being." },
  { phrase: "from now on", meaning: "从现在起", example: "I'll work harder from now on." },
  { phrase: "from time to time", meaning: "不时；偶尔", example: "We meet from time to time." },
  { phrase: "get along with", meaning: "与…相处；进展", example: "She gets along well with everyone." },
  { phrase: "get away", meaning: "离开；逃脱", example: "The thief got away." },
  { phrase: "get in the way", meaning: "挡道；妨碍", example: "Don't let fear get in the way." },
  { phrase: "get off", meaning: "下车；离开；动身", example: "Get off at the next stop." },
  { phrase: "get on", meaning: "上车；进展；相处", example: "How are you getting on?" },
  { phrase: "get over", meaning: "克服；恢复；从…中走出来", example: "I need to get over my fear." },
  { phrase: "get rid of", meaning: "摆脱；除去", example: "I can't get rid of this cold." },
  { phrase: "get through", meaning: "完成；通过(考试)；接通电话", example: "I finally got through the exam." },
  { phrase: "give away", meaning: "赠送；泄露", example: "She gave away all her old clothes." },
  { phrase: "give in", meaning: "屈服；让步", example: "Don't give in to pressure." },
  { phrase: "give off", meaning: "发出；放出(光、热、气味等)", example: "The fire gives off heat." },
  { phrase: "give out", meaning: "分发；用完；耗尽", example: "My money gave out." },
  { phrase: "give up", meaning: "放弃；戒除", example: "Never give up your dreams." },
  { phrase: "go ahead", meaning: "前进；继续；做吧", example: "Go ahead, don't wait." },
  { phrase: "go in for", meaning: "参加；从事；爱好", example: "He goes in for swimming." },
  { phrase: "go off", meaning: "爆炸；响起；离开", example: "The alarm went off at six." },
  { phrase: "go on", meaning: "继续；发生；进行", example: "What's going on?" },
  { phrase: "go out", meaning: "外出；熄灭；过时", example: "The fire went out." },
  { phrase: "go over", meaning: "仔细检查；复习", example: "Let's go over the plan." },
  { phrase: "go through", meaning: "经历；仔细检查；穿过", example: "He went through a difficult time." },
  { phrase: "go up", meaning: "上升；上涨；被建造", example: "Prices are going up." },
  { phrase: "hand in", meaning: "上交；递交", example: "Please hand in your homework." },
  { phrase: "hand out", meaning: "分发；施舍", example: "The teacher handed out worksheets." },
  { phrase: "have (something) to do with", meaning: "与…有关", example: "What does this have to do with me?" },
  { phrase: "have in mind", meaning: "想到；考虑到；打算", example: "What do you have in mind?" },
  { phrase: "hold on", meaning: "等一下；坚持住；别挂断", example: "Hold on a minute!" },
  { phrase: "hold up", meaning: "举起；支撑；耽搁", example: "Sorry, we were held up in traffic." },
  { phrase: "how come", meaning: "怎么会…？为什么…？", example: "How come you are late?" },
  { phrase: "in a hurry", meaning: "匆忙地；急于", example: "She left in a hurry." },
  { phrase: "in a sense", meaning: "在某种意义上", example: "In a sense, you are right." },
  { phrase: "in addition", meaning: "此外；而且", example: "In addition, we need more staff." },
  { phrase: "in advance", meaning: "提前；预先", example: "Please let me know in advance." },
  { phrase: "in any case", meaning: "无论如何；总之", example: "In any case, we must go." },
  { phrase: "in brief", meaning: "简而言之", example: "In brief, the plan failed." },
  { phrase: "in case", meaning: "以防；万一", example: "Take an umbrella in case it rains." },
  { phrase: "in charge of", meaning: "负责；主管", example: "Who is in charge of this project?" },
  { phrase: "in common", meaning: "共同的；共有的", example: "We have a lot in common." },
  { phrase: "in comparison with", meaning: "与…比较", example: "In comparison with last year, we improved." },
  { phrase: "in debt", meaning: "欠债；负债", example: "He is in debt to the bank." },
  { phrase: "in detail", meaning: "详细地", example: "Tell me the story in detail." },
  { phrase: "in fact", meaning: "事实上，实际上", example: "In fact, I disagree." },
  { phrase: "in favour of", meaning: "支持；赞同；有利于", example: "I'm in favour of the new policy." },
  { phrase: "in front of", meaning: "在…前面", example: "The bus stops in front of the school." },
  { phrase: "in general", meaning: "通常；大体上", example: "In general, people are friendly." },
  { phrase: "in hono(u)r of", meaning: "为了向…表示敬意；为庆祝", example: "A party was given in his honour." },
  { phrase: "in no time", meaning: "立刻；马上", example: "I'll be back in no time." },
  { phrase: "in order to", meaning: "为了；以便", example: "She studied hard in order to pass." },
  { phrase: "in particular", meaning: "特别；尤其", example: "I like travelling, in particular to Asia." },
  { phrase: "in person", meaning: "亲自；本人", example: "Come and see me in person." },
  { phrase: "in place of", meaning: "代替", example: "Use honey in place of sugar." },
  { phrase: "in practice", meaning: "在实践中；实际上", example: "The idea works well in practice." },
  { phrase: "in public", meaning: "公开地；当众", example: "He is afraid to speak in public." },
  { phrase: "in regard to", meaning: "关于；至于", example: "In regard to your question, here is my answer." },
  { phrase: "in return", meaning: "作为回报", example: "He gave me a gift in return." },
  { phrase: "in short", meaning: "简而言之；总之", example: "In short, it was a disaster." },
  { phrase: "in spite of", meaning: "尽管；不管", example: "In spite of the rain, we went out." },
  { phrase: "in terms of", meaning: "就…而言；在…方面", example: "In terms of money, we are fine." },
  { phrase: "in the distance", meaning: "在远处", example: "We saw a light in the distance." },
  { phrase: "in the end", meaning: "最后；终于", example: "In the end, everything was fine." },
  { phrase: "in the first place", meaning: "首先；最初", example: "Why did you come here in the first place?" },
  { phrase: "in the future", meaning: "未来；今后", example: "Be careful in the future." },
  { phrase: "in the meantime", meaning: "在此期间；与此同时", example: "We'll wait; in the meantime, have some coffee." },
  { phrase: "in the way", meaning: "挡道的；妨碍人的", example: "You're in the way." },
  { phrase: "in turn", meaning: "依次；反过来", example: "Each student speaks in turn." },
  { phrase: "in vain", meaning: "徒劳地；白白地", example: "We tried, but in vain." },
  { phrase: "in view of", meaning: "考虑到；鉴于", example: "In view of the weather, we cancelled." },
  { phrase: "instead of", meaning: "代替；而不是", example: "Walk instead of driving." },
  { phrase: "just now", meaning: "刚才；此刻", example: "He left just now." },
  { phrase: "keep off", meaning: "让开；不接近", example: "Keep off the grass." },
  { phrase: "keep on", meaning: "继续(做某事)；坚持", example: "Keep on trying!" },
  { phrase: "keep up with", meaning: "跟上；不落后；保持联系", example: "I try to keep up with the news." },
  { phrase: "kind of", meaning: "有点；有几分", example: "I'm kind of tired." },
  { phrase: "lay down", meaning: "放下；规定；制定", example: "They laid down strict rules." },
  { phrase: "lead to", meaning: "导致；通向", example: "Hard work leads to success." },
  { phrase: "learn by heart", meaning: "记住；背熟", example: "Learn the poem by heart." },
  { phrase: "leave alone", meaning: "不打扰；让独自待着", example: "Leave me alone!" },
  { phrase: "let down", meaning: "放下；使失望", example: "I won't let you down." },
  { phrase: "let out", meaning: "释放；发出(声音)；泄露", example: "Let out a sigh." },
  { phrase: "line up", meaning: "排队；列队", example: "People were lining up for tickets." },
  { phrase: "little by little", meaning: "逐渐地；一点一点地", example: "Little by little, he improved." },
  { phrase: "live on", meaning: "以…为主食；靠…生活；继续存在", example: "They live on a small income." },
  { phrase: "long for", meaning: "渴望；向往", example: "She longed for a rest." },
  { phrase: "look after", meaning: "照顾；照料", example: "Can you look after my cat?" },
  { phrase: "look down upon", meaning: "看不起；轻视", example: "Don't look down upon the poor." },
  { phrase: "look for", meaning: "寻找", example: "I'm looking for my phone." },
  { phrase: "look forward to", meaning: "期待；盼望", example: "I look forward to meeting you." },
  { phrase: "look into", meaning: "调查；研究", example: "The police are looking into the case." },
  { phrase: "look out", meaning: "留神；注意", example: "Look out! There's a car coming." },
  { phrase: "look over", meaning: "检查；查看", example: "Look over the report." },
  { phrase: "look up", meaning: "查阅；仰望；好转", example: "Look up the word in a dictionary." },
  { phrase: "lose heart", meaning: "丧失信心；灰心", example: "Don't lose heart!" },
  { phrase: "lose one's temper", meaning: "发脾气", example: "He lost his temper." },
  { phrase: "make a difference", meaning: "有影响；起作用", example: "Your help made a big difference." },
  { phrase: "make for", meaning: "走向；有利于；导致", example: "The ship made for the shore." },
  { phrase: "make fun of", meaning: "取笑；嘲笑", example: "Don't make fun of others." },
  { phrase: "make out", meaning: "辨认出；理解；填写", example: "I can't make out his handwriting." },
  { phrase: "make sense", meaning: "有意义；讲得通；明智", example: "Does that make sense?" },
  { phrase: "make sure", meaning: "确保；查明", example: "Make sure the door is locked." },
  { phrase: "make up", meaning: "编造；弥补；化妆；组成", example: "He made up an excuse." },
  { phrase: "make up one's mind", meaning: "下定决心", example: "I can't make up my mind." },
  { phrase: "more or less", meaning: "或多或少；大约", example: "It's more or less finished." },
  { phrase: "no doubt", meaning: "毫无疑问；很可能", example: "No doubt he will come." },
  { phrase: "no longer", meaning: "不再", example: "I can wait no longer." },
  { phrase: "no matter", meaning: "不管；无论", example: "No matter what happens, stay calm." },
  { phrase: "not only ... but also", meaning: "不仅…而且…", example: "He not only sings but also dances." },
  { phrase: "now that", meaning: "既然；由于", example: "Now that you're here, let's begin." },
  { phrase: "of course", meaning: "当然；自然", example: "Of course I'll help." },
  { phrase: "off and on", meaning: "断断续续地；有时", example: "It rained off and on all day." },
  { phrase: "on account of", meaning: "因为；由于", example: "They cancelled on account of the weather." },
  { phrase: "on average", meaning: "平均；通常", example: "On average, we work 40 hours a week." },
  { phrase: "on behalf of", meaning: "代表；为了", example: "I'm here on behalf of the team." },
  { phrase: "on board", meaning: "在船（飞机、火车）上；加入", example: "Welcome on board!" },
  { phrase: "on condition that", meaning: "如果；在…条件下", example: "I'll come on condition that Mary is invited." },
  { phrase: "on duty", meaning: "值班；值勤", example: "Who's on duty today?" },
  { phrase: "on earth", meaning: "究竟；到底", example: "What on earth is that?" },
  { phrase: "on foot", meaning: "步行", example: "We went there on foot." },
  { phrase: "on purpose", meaning: "故意地", example: "He did it on purpose." },
  { phrase: "on the contrary", meaning: "正相反", example: "It's not boring; on the contrary, it's exciting." },
  { phrase: "on the one hand", meaning: "一方面", example: "On the one hand, it's cheap; on the other, it's low quality." },
  { phrase: "on the other hand", meaning: "另一方面", example: "On the other hand, we could save money." },
  { phrase: "on the whole", meaning: "总的来看；大体上", example: "On the whole, I'm satisfied." },
  { phrase: "once in a while", meaning: "偶尔；间或", example: "We go out once in a while." },
  { phrase: "one another", meaning: "互相（三者及以上）", example: "The team members help one another." },
  { phrase: "or else", meaning: "否则；不然", example: "Hurry up, or else you'll be late." },
  { phrase: "out of", meaning: "从…向外；由于；缺乏；脱离", example: "We're out of milk." },
  { phrase: "out of date", meaning: "过时的；不用的", example: "This technology is out of date." },
  { phrase: "out of order", meaning: "出故障；次序颠倒", example: "The lift is out of order." },
  { phrase: "out of place", meaning: "不适当的；不在原来的位置", example: "His joke was out of place." },
  { phrase: "out of sight", meaning: "看不见；在视野之外", example: "The plane flew out of sight." },
  { phrase: "owing to", meaning: "由于；因为", example: "Owing to the storm, the flight was delayed." },
  { phrase: "pass away", meaning: "去世；消失", example: "His grandfather passed away last year." },
  { phrase: "pay attention to", meaning: "注意；留心", example: "Pay attention to the road." },
  { phrase: "pay back", meaning: "偿还；报复", example: "I'll pay you back tomorrow." },
  { phrase: "pay for", meaning: "付款；为…付出代价", example: "You'll pay for this mistake." },
  { phrase: "pick out", meaning: "挑选；辨认出", example: "Can you pick out your mother in the photo?" },
  { phrase: "pick up", meaning: "捡起；接(人)；学会；好转", example: "Pick up the phone!" },
  { phrase: "point out", meaning: "指出；指明", example: "He pointed out my mistake." },
  { phrase: "point of view", meaning: "观点；看法", example: "From my point of view, it's unfair." },
  { phrase: "prevent … from", meaning: "阻止…做…", example: "The rain prevented us from going out." },
  { phrase: "prior to", meaning: "在…之前", example: "Prior to the meeting, we discussed the agenda." },
  { phrase: "provide … with", meaning: "为…提供…", example: "The hotel provides guests with free breakfast." },
  { phrase: "put forward", meaning: "提出；建议", example: "He put forward a new idea." },
  { phrase: "put off", meaning: "推迟；拖延；使反感", example: "Don't put off your homework." },
  { phrase: "put on", meaning: "穿上；上演；增加(体重)", example: "Put on your coat." },
  { phrase: "put out", meaning: "熄灭；伸出；生产；使苦恼", example: "Please put out your cigarette." },
  { phrase: "put up", meaning: "搭建；举起；张贴；留宿", example: "We put up a tent." },
  { phrase: "put up with", meaning: "忍受；容忍", example: "I can't put up with this noise." },
  { phrase: "quite a few", meaning: "相当多；不少", example: "Quite a few people came." },
  { phrase: "rather than", meaning: "而不是；与其…倒不如", example: "I'd go out rather than stay at home." },
  { phrase: "refer to", meaning: "提到；参考；指的是", example: "This refers to the previous sentence." },
  { phrase: "regardless of", meaning: "不顾；不管", example: "He went regardless of the danger." },
  { phrase: "rely on", meaning: "依靠；信赖", example: "I rely on you for support." },
  { phrase: "remind … of", meaning: "使…想起；提醒", example: "You remind me of your father." },
  { phrase: "result in", meaning: "导致；造成", example: "The accident resulted in three deaths." },
  { phrase: "right away", meaning: "立刻；马上", example: "I'll be there right away." },
  { phrase: "run across", meaning: "偶然遇见；跑过", example: "I ran across an old friend." },
  { phrase: "run out (of)", meaning: "用完；耗尽", example: "We've run out of bread." },
  { phrase: "see off", meaning: "送别；给…送行", example: "They came to see me off." },
  { phrase: "see to", meaning: "负责；处理；照料", example: "Please see to the luggage." },
  { phrase: "send for", meaning: "派人去请；召唤", example: "We sent for a doctor." },
  { phrase: "set about", meaning: "开始做；着手", example: "We set about cleaning the house." },
  { phrase: "set aside", meaning: "留出；拨出；把…放一旁", example: "Set aside some money for emergencies." },
  { phrase: "set off", meaning: "出发；引起；使爆炸", example: "We set off early in the morning." },
  { phrase: "set out", meaning: "出发；开始；陈述", example: "They set out on a journey." },
  { phrase: "set up", meaning: "建立；设立；安排", example: "He set up his own business." },
  { phrase: "show off", meaning: "炫耀；卖弄", example: "Don't show off your knowledge." },
  { phrase: "side by side", meaning: "肩并肩地；一起", example: "They walked side by side." },
  { phrase: "so far", meaning: "到目前为止；迄今为止", example: "So far, so good." },
  { phrase: "so long as", meaning: "只要", example: "You may go, so long as you come back early." },
  { phrase: "sooner or later", meaning: "迟早；早晚", example: "Sooner or later, you'll understand." },
  { phrase: "stand for", meaning: "代表；支持；容忍", example: "What does UN stand for?" },
  { phrase: "stand out", meaning: "突出；显眼；杰出", example: "Her talent stands out." },
  { phrase: "stick to", meaning: "坚持；粘在…上", example: "Stick to your plan." },
  { phrase: "such as", meaning: "例如；像…这样", example: "Fruits such as apples and oranges." },
  { phrase: "sum up", meaning: "总结；概括", example: "To sum up, it was a success." },
  { phrase: "switch off", meaning: "关掉；切断(电源)", example: "Please switch off the light." },
  { phrase: "switch on", meaning: "打开；接通(电源)", example: "Switch on the radio." },
  { phrase: "take … into account", meaning: "考虑到；顾及", example: "You must take his experience into account." },
  { phrase: "take advantage of", meaning: "利用；占…的便宜", example: "Take advantage of the opportunity." },
  { phrase: "take care", meaning: "当心；保重", example: "Take care of yourself." },
  { phrase: "take care of", meaning: "照顾；处理", example: "I'll take care of the children." },
  { phrase: "take charge of", meaning: "负责；掌管", example: "She took charge of the project." },
  { phrase: "take down", meaning: "记下；拆掉；拿下", example: "Take down my phone number." },
  { phrase: "take for", meaning: "把…误认为是；把…看作", example: "I took him for a doctor." },
  { phrase: "take in", meaning: "吸收；理解；欺骗", example: "I couldn't take in all the information." },
  { phrase: "take it easy", meaning: "别着急；放松", example: "Take it easy, everything will be fine." },
  { phrase: "take off", meaning: "起飞；脱下；离开", example: "The plane took off on time." },
  { phrase: "take on", meaning: "承担；呈现；雇佣", example: "He took on too much work." },
  { phrase: "take over", meaning: "接管；接替", example: "He took over the family business." },
  { phrase: "take part in", meaning: "参加；参与", example: "We took part in the discussion." },
  { phrase: "take place", meaning: "发生；举行", example: "The ceremony took place yesterday." },
  { phrase: "take up", meaning: "开始从事；占据；拿起", example: "She took up painting." },
  { phrase: "talk over", meaning: "讨论；商量", example: "Let's talk it over." },
  { phrase: "thanks to", meaning: "多亏；由于", example: "Thanks to his help, we finished on time." },
  { phrase: "that is to say", meaning: "也就是说", example: "He's very busy; that is to say, he has no time." },
  { phrase: "the moment (that)", meaning: "一…就…", example: "The moment I saw her, I knew." },
  { phrase: "think of", meaning: "想起；考虑；认为", example: "What do you think of the plan?" },
  { phrase: "think over", meaning: "仔细考虑", example: "Think it over before you decide." },
  { phrase: "throw away", meaning: "扔掉；浪费；错过", example: "Don't throw away this chance." },
  { phrase: "to some extent", meaning: "在某种程度上", example: "I agree to some extent." },
  { phrase: "try on", meaning: "试穿；试戴", example: "Can I try on this dress?" },
  { phrase: "turn down", meaning: "关小；调低；拒绝", example: "He turned down the offer." },
  { phrase: "turn off", meaning: "关掉；关闭", example: "Turn off the TV." },
  { phrase: "turn on", meaning: "打开；接通；取决于", example: "Turn on the light." },
  { phrase: "turn out", meaning: "结果是；证明是；生产；出动", example: "It turned out to be true." },
  { phrase: "turn over", meaning: "翻转；移交；营业额达到", example: "Turn over the page." },
  { phrase: "turn to", meaning: "转向；求助于；翻到", example: "He turned to his friend for help." },
  { phrase: "under control", meaning: "处于控制之下", example: "The fire is now under control." },
  { phrase: "up to", meaning: "直到；多达；取决于；胜任", example: "It's up to you." },
  { phrase: "use up", meaning: "用完；耗尽", example: "We used up all the paper." },
  { phrase: "wait for", meaning: "等待；等候", example: "I'm waiting for the bus." },
  { phrase: "wake up", meaning: "醒来；唤醒", example: "Wake me up at seven." },
  { phrase: "watch out", meaning: "当心；提防", example: "Watch out for snakes!" },
  { phrase: "wear off", meaning: "逐渐消失；磨掉", example: "The effect of the drug wore off." },
  { phrase: "what is more", meaning: "更重要的是；而且", example: "He is smart, and what is more, he is kind." },
  { phrase: "wipe out", meaning: "彻底消灭；擦掉", example: "The disease was wiped out." },
  { phrase: "with regard to", meaning: "关于；至于", example: "With regard to your query, we will reply soon." },
  { phrase: "with the exception of", meaning: "除…之外", example: "Everything was perfect, with the exception of the weather." },
  { phrase: "without exception", meaning: "毫无例外", example: "Everyone, without exception, must attend." },
  { phrase: "word for word", meaning: "逐字地", example: "Tell me what he said, word for word." },
  { phrase: "work out", meaning: "计算出；解决；锻炼；制定", example: "We need to work out a solution." },
  { phrase: "worry about", meaning: "担心；担忧", example: "Don't worry about me." },
  { phrase: "would rather", meaning: "宁愿；宁可", example: "I would rather stay home." },
  { phrase: "write down", meaning: "写下；记下", example: "Write down the address." }
];
